### ISSUE TITLE
Migration from OpenWebAnalytics

### ISSUE THREAD

**Issue by mxstbr** [usefathom/fathom#1]
I'm currently running an OpenWebAnalytics server, but would love to switch that over to ana! Any ideas if migration will ever be possible?

**Comment by dannyvankooten** [comment]
Hey @mxstbr, thanks for expressing interest! Ana is still in a very early stage right now but I'll be steadily working on it over the course of the next few months to turn this into something usable & stable. Actually just implemented Ana on a few production sites today so the next few weeks / months will be pretty important.

I'm keeping a close eye on Google Analytics, Piwik & Open Web Analytics so will definitely look at providing migration options for those three. Do you happen to know if the OWA project is discontinued or are you having any specific problems with it?

**Comment by mxstbr** [comment]
I haven't seen an update in a long time. I don't know if it's been actively deprecated, but it's definitely not in a state where I would recommend it over Piwik for self hosted analytics.

Glad to hear you're going to look into this, definitely excited for this project!

**Comment by horejsek** [comment]
@dannyvankooten Hi. I use GA, tried to deploy Fathom, looks very good and now I'm thinking about killing GA, but before that I would love to migrate old data. It doesn't have to be super precise. Is there any tool or do you plan to use it? If not, I saw that if I would export some CSV from GA and wrote small script to insert data into pageviews table, it could maybe work, am I correct, what should be done to not break it? :-)

**Comment by JackEllis** [comment]
This is on the roadmap. May happen in the future. I think the solution is to allow a generic format to be uploaded, leaving some re-structuring work to the user, but allowing wider support.
