### ISSUE TITLE
User journey flow view

### ISSUE THREAD

**Issue by BlueHatbRit** [usefathom/fathom#105]
Loving Fathom, I've got it running along side Google Analytics at the moment while I slowly transition my sites over to Fathom.

I was wondering if there had been any thought into some sort of user journey flow like the GA Behaviour Flow. It would be very useful to know where users go once landing on a particular page and seeing that drop off would be invaluable to understand how users navigate my sites. I'm sure this feature is pretty involved as the charts to display it would be fairly tough to product probably, but it'd be good to get a feel for if this idea has come up before, and if so where it's at.

**Comment by pjrvs** [comment]
Yes, we're working on tracking trends in activity + flows as a future feature.

I'm going ahead and will close this issue to keep the issue list clean with actual issues instead of stuff to put on the roadmap, but please don't think that means we won't ever think about making this feature :)
