### ISSUE TITLE
Hourly graph on the "Today" view

### ISSUE THREAD

**Issue by BlueHatbRit** [usefathom/fathom#107]
Last feature suggestion, I swear! It would be really good to have the same graph that's on the other views, but on the "Today" view representing across hours. It would be very useful to see when people are hitting my site so I can figure out roughly what timezones folks might be in, or to figure out how my social posts might contribute to page views.

**Comment by pjrvs** [comment]
That's definitely a good idea! @dannyvankooten and I will talk about that (and as I said, possibly add it to our roadmap). Cheers and thanks so much for your suggestions today!
