### ISSUE TITLE
Profile Web Crawlers

### ISSUE THREAD

**Issue by jhabdas** [usefathom/fathom#108]
Provide a count of Web Crawlers visiting the site and overlay the data on the chart.

**Comment by dannyvankooten** [comment]
Hello @jhabdas,

Can you elaborate a bit on why you think this is useful and why site owners should have to know or care about this?

Right now, web crawlers are dismissed and not being counted at all. I honestly feel like log parsing would be a better solution for counting crawlers, as the only people that should really care about that stuff are also probably technical enough to run a log parser? Thoughts @pjrvs?

**Comment by pjrvs** [comment]
Agreed @dannyvankooten - I'm fine with crawlers being dismissed and not counted in fathom.

**Comment by jhabdas** [comment]
SGTM. Thanks!
