### ISSUE TITLE
Docker image Versioning

### ISSUE THREAD

**Issue by t3hmrman** [usefathom/fathom#109]
Hey I know this project is in early stages, but could you start versioning at the very least the docker images [in docker hub](https://hub.docker.com/r/usefathom/fathom/tags)? 

I'm recently going through setting up Fathom and I'd rather not rely on `latest` (as in `usefathom/fathom:latest`), but it's the only docker tag right now. Even date of build would be fine and if you guys have build automation you could use just the date of the build...

**Comment by dannyvankooten** [comment]
Hey @t3hmrman,

You're absolutely right - will look into setting that up properly!

**Comment by t3hmrman** [comment]
hey @dannyvankooten No problem! Also if you want to take a quick run through at how I fared (I filed one more ticket #110 ) [I wrote about it](https://vadosware.io/post/kicking-the-tires-on-fathom/).

Thanks for all the great work on Fathom!
