### ISSUE TITLE
Latest release old

### ISSUE THREAD

**Issue by raunsbaekdk** [usefathom/fathom#111]
Hi @dannyvankooten 

The latest release (https://github.com/usefathom/fathom/releases/tag/latest) is from May even though it mentions that it is being updated weekly.

**Comment by pjrvs** [comment]
We're doing our best, and currently working on a lot of things behind the scenes for Fathom.

**Comment by dannyvankooten** [comment]
Hi @raunsbaekdk,

The binaries attached to that release are actually up to date, but GitHub doesn’t update the timestamp when just replacing the attachments.

I’ll make sure to add a “last updated” timestamp in text instead, I can see how that’d be useful.

Cheers!

Verstuurd vanaf mijn iPhone

**Comment by raunsbaekdk** [comment]
Hi @pjrvs 

I know that.

Thanks @dannyvankooten for constructive feedback. :-)

**Comment by dewey** [comment]
@dannyvankooten not sure if you are aware of it but https://goreleaser.com is great to release often and mostly automated (just have to tag the commit you want to have the release at and then run goreleaser). It's a lot less of a hassle to get a new release out with that. That would make the release numbers more helpful especially for people to debug and compare versions and also it would make it easier to follow development than checking the timestamps of the "umbrella" 1.0 release.

**Comment by dannyvankooten** [comment]
Hi @dewey,

Haven't used goreleaser yet but have definitely come across it before - thank you, we'll be considering that! 

But to clarify: 1.0.0 is not actually an umbrella release, it is the latest tagged stable version and we'll be adhering to a semver(ish) versioning scheme from now on. The timestamp is actually only necessary for the [latest release](https://github.com/usefathom/fathom/releases/tag/latest), which we provided to make it easier for people to run the latest GitHub master without having to compile for themselves (for people that want to help test and/or are feeling adventurous).
