### ISSUE TITLE
Latest release?

### ISSUE THREAD

**Issue by ziburski** [usefathom/fathom#112]
There have been a lot of fixes / improvements since the first release, but I don’t see an updated official release yet. Am I missing something with the [installation instructions](https://github.com/usefathom/fathom/wiki/Installing-&-running-Fathom), or is an updated binary coming later?

Thank you!

**Comment by dannyvankooten** [comment]
Not missing anything, we have yet to tag a new version.

That said, you can download precompiled binaries for the latest GitHub master at any time by heading over to the ["latest" release](https://github.com/usefathom/fathom/releases/tag/latest).

Sorry I didn't get around to tagging something yet - we're super busy finalising our hosted Fathom offering these weeks.
