### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by ziburski** [usefathom/fathom#115]
Hi. I was just about to throw my hands up in the air and create an issue, when I noticed that the code on [this page](https://github.com/usefathom/fathom/wiki/Running-Fathom-as-a-service) is updated, whereas I was using the older code for launching Fathom on boot on the main [installation instructions](https://github.com/usefathom/fathom/wiki/Installing-&-running-Fathom).

Adding `RestartSec=6` to the script fixed my issues, it would be nice to include that in both versions. Or just link to the updated wiki page.

**Comment by dannyvankooten** [comment]
Hey @ziburski,

I've updated the installation instructions to include that line, but think there is a better way of going about this. The `RestartSec` line is really just a catch-all solution as it gives the script some leeway to retry after other depending factors have booted up.

In your case, could it be that you're using Fathom with either Postgres or MySQL? In that case, I would change the line that reads:

```
After=network.target
```

Into (for MySQL):
```
After=network.target mysql.service
```

Or for Postgres:
```
After=network.target postgresql.service
```

That will ensure that the system will only attempt to start Fathom after the database service has booted up, meaning you can get rid of the time delay set by `RestartSec`.

Cheers!
