### ISSUE TITLE
Realtime visitor count is inflated when generating pageviews with a duration of 0s

### ISSUE THREAD

**Issue by dannyvankooten** [usefathom/fathom#123]
Because we check the `duration` or `is_bounce` column. A cleaner way would probably be to include a boolean column indicating whether that pageview is done (ready to be aggregated) and not repeating that logic throughout the codebase.

**Comment by dannyvankooten** [comment]
@m1guelpf Sure thing!

When a pageview is first received, it is stored with a `Duration: 0` and `IsBounce: true` properties. 

Then when the next pageview by that same visitor is recorded, the request includes the ID of the previous pageview. We use that to update the previous pageview as we can now calculate the "time on page" by diff'ing the two timestamps. We also know it is not a bounce,  as another pageview followed.

This issue is caused when two pageviews are generated very quick after each other, so that the difference between the two timestamps is `0` (or very close to zero, since this is an `INTEGER` column).

A separate boolean column that is toggled whenever a pageview is updated would fix this, so we can use that column instead of checking for `duration = 0 AND is_bounce = FALSE`.

**Comment by m1guelpf** [comment]
Wouldn't this be fixed by setting a minimum of 1sec in the timestamp substraction?

**Comment by dannyvankooten** [comment]
That would inflate the "time on page" metric, as the current implementation discards pageviews with a duration of `0`. 

I think that A point could be made to turn the duration column into an integer so we can store fractional values like 0.xxxxxx, but I feel an additional column indicating whether a pageviews is ready to be aggregated would be the best seperation of concerns here (and simplifying logic throughout rest of codebase).

**Comment by SleeplessByte** [comment]
FWIW: this is still an issue. After "quickly" navigating my current visitor count went in the 30+, when it was just me. Later, it did correctly show 1 visitor.
