### ISSUE TITLE
Disable dashboard animations (via client-side setting)

### ISSUE THREAD

**Issue by sandebert** [usefathom/fathom#125]
I realize it's meant to make Fathom look slick, and it succeeds with that.

However, to me it also makes the UI feel slow, and I find it difficult to compare values. For example: It's a lot easier if I can click `LAST 7 DAYS` and then `LAST 30 DAYS` and instantly see the changes without seeing a whirlwind of other numbers in-between.

(If CountWidget is meant to help me get a feeling for if the numbers gone down or up, I'd instead suggest adding a small up/down arrow to the right of each number, that fades away in a sec or so. That would instantly give a "yeah, those numbers are going down, but that one is going up” insight. Let me know if I should add a small pic to illustrate.)

**Comment by dannyvankooten** [comment]
Hi @sandebert,

Would an option (saved in your browser) somewhere in the interface to disable all animations be helpful for you, or is it just the specific number animation that you don't enjoy?

**Comment by sandebert** [comment]
Hi @dannyvankooten,

You're thinking of the ”growing” of the bars in the chart, right? Yeah, if it's simple to remove all animations/fades/etc that would be great. I love me _snappy_ interfaces. And having an option that is saved in my browser would work just fine for me, if it's a simple enough solution for you. 

And making a wild guess, I can imagine it might also be simple for you to add something to the `.env` file? Something like `FATHOM_UI_ANIMATIONS=false`? If that would be possible, it would be even nicer, so I could do it for all users in one swift move. But I'll settle for the browser solution if that's something you prefer.

Thanks for considering it. :)

**Comment by pjrvs** [comment]
I'm not personally tied to the animations (the UI animations or the "counting" ones). I just don't want to get into a long list of env variables at setup.

So I'm ok to get a general consensus on this and call it closed (and apologize to the folks who weren't the majority).

**Comment by sandebert** [comment]
> I just don't want to get into a long list of env variables at setup.

Yeah, I can understand that aspect. Simple _is_ beautiful. 

I realize you probably already thought about this, but I thought I'd mention that you could wire things so that if `FATHOM_UI_ANIMATIONS=false` you disable them. And not even having that variable in the config makes it default to true. So, no extra config for the folks loving them animations.

**Comment by JackEllis** [comment]
No complaints in the last 6 months so closing this up.
