### ISSUE TITLE
Don’t track prerendered pages

### ISSUE THREAD

**Issue by da2x** [usefathom/fathom#13]
Web browsers automatically prefetch or even prerender web pages in the background on behalf of the user. The user may never see the page, so they should make sure to exclude them from analytics.

Chrome: `('visibilityState' in document && document.visibilityState=='prerender')`

Firefox: `X-Moz: prefetch` (HTTP request header)

Safari: `X-Purpose: preview` (HTTP request header)

Edge: undetectable

**Comment by dannyvankooten** [comment]
Great tip, thanks @da2x.

Looking at [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) and [caniuse](https://caniuse.com/pagevisibility), I can't seem to find anything on `document.visibilityState` not having the `prerender` value in Firefox or Safari. Could you shed some light on that for me please?

**Comment by da2x** [comment]
@dannyvankooten, my only data point is my own custom tracker. It submits `onpageunload` and checks `('visibilityState' in document && document.visibilityState=='prerender')` before doing a `sendBeacon()`. I still see `X-Moz` and `X-Purpose` submissions despite the check.
