### ISSUE TITLE
Public Dashboard

### ISSUE THREAD

**Issue by bradders** [usefathom/fathom#130]
Any plans to have an option for users to make their dashboard public (like the Fathom marketing site)?

Not a blocker, or a dealbreaker, but I'm toying with the idea of opening up my stats on a site that is open with the rest of its data.

Or maybe this ties more into the API trello card, in that I could just use the API to pull stats onto the site, instead of directing people to my `x.usesfathom` instance. 🤔

**Comment by dannyvankooten** [comment]
Hey @bradders,

This is already a feature, we have yet to build it into our hosted offering though. Fathom will act as a public dashboard if there are no users registered.

Just let me know if and when you want to open-up your Fathom dashboard, and I'll take care of it manually for you. You'll be able to do it yourself in just a few weeks too, when we build out our user management feature.

**Comment by bradders** [comment]
🙌

**Comment by dannyvankooten** [comment]
@weavermedia It is, but we'll have to enable it manually for you for the time being. 

If you want your dashboard to be public, please send us an email with your dashboard URL at support@usefathom.com. Please note that public dashboards lack certain features like the ability to add additional sites, so make sure you have all the sites you need before making the dashboard public.

**Comment by Mobilpadde** [comment]
@dannyvankooten how would I enable it manually on the hosted version? :+1:

**Comment by Mobilpadde** [comment]
@dannyvankooten how would I enable it manually on the self-hosted version? :+1:

**Comment by dannyvankooten** [comment]
@Mobilpadde 

To make a public dashboard private, simply create at least one user account.

```
fathom user add --email=your@email.com --password=secret
```

To make a private dashboard public, delete all user accounts:

```
fathom user delete --email=you@email.com
```
