### ISSUE TITLE
Better Notification for Wrong Password

### ISSUE THREAD

**Issue by EdwardGoomba** [usefathom/fathom#131]
Currently when trying to log into your Fathom dashboard - if you input the wrong password the only notification you get is a '401' at the top of the page. This will cause confusion - for example, if I am sending a client a dashboard login, they are going to be clueless as to why they cannot login.

Would be nice to change this to 'Wrong Password' or something similar.

Note: Only tried with hosted version of Fathom.

**Comment by dannyvankooten** [comment]
Hey Edward,

100% agree - it’s been on the list for a while now. About time I get to it!

**Comment by pjrvs** [comment]
If you want me to mock up error messages on that login form, I can do that for you to implement @dannyvankooten :)

**Comment by dannyvankooten** [comment]
Yes please, that'd be great @pjrvs!
