### ISSUE TITLE
Timezone issues

### ISSUE THREAD

**Issue by dannyvankooten** [usefathom/fathom#134]
While storing statistics on a daily basis in UTC dates has upsides, it has two pretty big downsides:

- For people ahead of UTC, their "today" view will always be empty if they're checking their stats early on in the day.
- For people behind UTC, their "today" view will be finished already while stats are already being collected for the next day if they're checking later on in their day.

An improvement would be to store statistics by the hour, that'll also give us a chart to show on the "today" view. It would increase storage size by a factor 24 however.

**Comment by jhabdas** [comment]
Sounds like a dashboard UI and tracking issue. My expectation would be to capture time in two ways:

- Absolute based on server with UTC offset based on host setting.
- Relative [based on the browser](https://redfin.engineering/getting-the-time-zone-from-a-web-browser-71e08dae9f89).

The latter of which would be used when viewing the dashboard to allow time traveling.

**Comment by dannyvankooten** [comment]
That is already how it works, the issue is that Fathom aggregates on a “daily” basis right now (so there is one data entry per UTC day) so we can’t take relative UTC offsets into account.

Verstuurd vanaf mijn iPhone
