### ISSUE TITLE
Specify minimal system requirements

### ISSUE THREAD

**Issue by hyperknot** [usefathom/fathom#137]
First of all, congrats for this fantastic project. One thing I missed though is that can you specify the minimum system requirements, possibly for all 3 database types? 

For example Discourse has a really nice writeup on really recommending a 2 GB instance for Discourse + Postgresql.

https://github.com/discourse/discourse/blob/master/docs/INSTALL.md

**Comment by dannyvankooten** [comment]
Hey @hyperknot,

Thanks for the suggestion, we'll add a few lines to the wiki. Fathom really doesn't need all that much hardware to run.

A single-core CPU with 1GB of RAM is plenty, as a Fathom instance using SQLite won't take up much more than 100MB of RAM for website with moderate (say, 100K pageviews per month) traffic.

Both PostgreSQL and MySQL take up more RAM by default but even those can run comfortably on a machine with 1GB of RAM.

So, to ballpark some figures:

#### Hardware Requirements

   - single-core CPU
   - 1 GB RAM 
   - 64-bit Linux 
   - 1GB disk space

**Comment by hyperknot** [comment]
Thanks! Also about SQLite the website says that for long term usage we shouldn't use SQLite. Is there anything inherently wrong with using SQLite why it's written?

**Comment by dannyvankooten** [comment]
Hi @hyperknot,

You're right - that comment makes no sense. I've changed it to be more accurate.

> If you're already running MySQL or PostgreSQL on the server you're installing Fathom on, you'll most likely want to use one of those as your database driver.

**Comment by lostfictions** [comment]
I was also wondering about this! Seems like this repo doesn't have a wiki (anymore?) -- did this info get deleted?
