### ISSUE TITLE
ALT + arrow-key doesn't work

### ISSUE THREAD

**Issue by RadhiFadlillah** [usefathom/fathom#138]
In the analytic page, it said "Use ALT + arrow-key to cycle through date ranges". However, in Firefox 62.0.2, Alt + row-key is already [used](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly) for shortcut, so it doesnt work as intended.

**Comment by dannyvankooten** [comment]
Hey @RadhiFadlillah,

That's weird, it definitely does for me in Firefox Nightly and Firefox itself and I can't find any default browser shortkey on that link either. (There is one for `Cmd + Alt + Arrow-key` but not without `Cmd` IIUC).

Could it be that it the shortkey isn't working because your browser window does not have focus?

**Comment by RadhiFadlillah** [comment]
Hi @dannyvankooten

> That's weird, it definitely does for me in Firefox Nightly and Firefox. I can't find any default browser shortkey on that link either.

I'm sorry, I forgot to tell that I'm using Firefox 62.0.2 in Manjaro Linux 64-bit. In Linux, Firefox uses Alt + Left for going back and Alt + Right for going forward :

![shortcut firefox](https://user-images.githubusercontent.com/6129042/46026435-87b41480-c115-11e8-9182-236e4f85e6ac.png)

AFAIK Chrome also uses the same [shortcut](https://support.google.com/chrome/answer/157179?hl=en) for Windows and Linux :

![shortcut-chrome](https://user-images.githubusercontent.com/6129042/46026518-c9dd5600-c115-11e8-8d67-1f6b2c5bc18c.png)

**Comment by bigblind** [comment]
I'ém willing to submit a PR for updating the shortcut. Any suggestions for what that should be?

**Comment by dannyvankooten** [comment]
@bigblind That'd be so awesome! I have yet to check what keys browsers deem safe to use in "user-land" but I was thinking of using the regular arrow-keys **unless** an input field has focus (if the event still fires then, I am not sure without checking).

**Comment by bigblind** [comment]
Ok, that should be easy to check using event.target.
