### ISSUE TITLE
The latest release doesn't follow the the install instructions in the wiki

### ISSUE THREAD

**Issue by mhanberg** [usefathom/fathom#146]
The [wiki](https://github.com/usefathom/fathom/wiki/Installing-&-running-Fathom) instructs you to install by downloading the binary

>wget https://github.com/usefathom/fathom/releases/download/latest/fathom-linux-amd64

This url no longer exists. According to the release page, there is `
https://github.com/usefathom/fathom/releases/download/latest-development/fathom-linux-amd6` and 
`https://github.com/usefathom/fathom/releases/download/1.0.1/fathom-linux-amd64-1.0.1`.

I'm not sure whether the wiki or the assets in the release need to be updated.

PS. Thanks for developing Fathom! I'm really liking it so far and I'm working on something to make it easier for others to get started.

**Comment by nektro** [comment]
The latest release is a pre-release so the URL is either
https://github.com/usefathom/fathom/releases/download/latest-development/fathom-linux-amd64
or https://github.com/usefathom/fathom/releases/download/1.0.1/fathom-linux-amd64-1.0.1

**Comment by nektro** [comment]
The `latest` tag did not have a binary attached to it. https://github.com/usefathom/fathom/releases/tag/latest

**Comment by dannyvankooten** [comment]
Whoops, missed a wiki page when attempting to fix #143. Sorry!
