### ISSUE TITLE
All-time view of page views?

### ISSUE THREAD

**Issue by nektro** [usefathom/fathom#149]
Presumably in this space:
![image](https://user-images.githubusercontent.com/5464072/46718363-fc6c7000-cc38-11e8-913c-1f576f331340.png)

**Comment by dannyvankooten** [comment]
Hey @nektro,

Can you explain a bit about why you think this is useful and warrants a spot in the presets? If it is only used occasionally, shouldn't the current approach suffice?

**Comment by weavermedia** [comment]
I'd like to see 'All-time' too. It's good to be able to see the whole progression of something from the very start. Stripe has something similar:

![screen shot 2018-11-04 at 10 33 45 pm](https://user-images.githubusercontent.com/3027787/47981788-0fc8fa80-e082-11e8-8784-d3e184ed7ab9.png)

**Comment by worldlywisdom** [comment]
+1 for this feature. It's very helpful for marketing claims, particularly for popular pages. (Example: I have a page that has been viewed 3+ million times, and keeping track of the total number is important to support claims associated with that number.)
