### ISSUE TITLE
is there a way to see the tracking snippet again?

### ISSUE THREAD

**Issue by lucasfischer** [usefathom/fathom#150]
is there a way to see the tracking snippet again?
after i updated the docker image the backend asked me to give my current site a name and showed me the tracking snippet afterwards. i clicked it away because i first wanted to add other domains, which i could not do, because i could not find a button to do so.

is there a way to see the tracking snippet again?
is it possible to add more sites at this moment?

ps: i guess this feature is currently still in development.

**Comment by dannyvankooten** [comment]
Hey Lucas, 

Your dashboard is presumably public, which means that you only see the “site settings” once until we build out that feature for public dashboards as well.

If you add a user to your installation then you will be able to add more sites. You can then later delete this user to make your dashboard public again.

We plan to improve on this very soon, lots of changing things right now!
