### ISSUE TITLE
Combined views

### ISSUE THREAD

**Issue by m1guelpf** [usefathom/fathom#151]
Now that we have sites, it'd be cool to have a tab where we can see the sum of all pageviews, etc

**Comment by dannyvankooten** [comment]
Hi @m1guelpf,

Can you elaborate why you need this data exactly? I’m afraid “cool” isn’t enough to warrant including this in Fathom.

**Comment by m1guelpf** [comment]
Yeah, sorry, let me ellaborate a bit more. Imagine I have different sites in different subdomains. I have different "sites" for each of them to group them by host and to segment the data. But then, I have to give the client the complete stats, or even better, give him access to a dashboard where he can see it.
