### ISSUE TITLE
[Request] IP & referral blacklist?

### ISSUE THREAD

**Issue by mgibbs189** [usefathom/fathom#154]
It'd be nice to be able to exclude / blacklist referrals (using regex) from getting logged or appearing in stats.

Same goes for IPs & IP ranges. When I visit my own site, I don't generally want my views to affect the stats. I know that Fathom is privacy-focused, and presumably checking the IP against a blacklist (without logging anything) wouldn't infringe against any rules.

**Comment by regpaq** [comment]
Was the ability to add our own IP addresses to the blacklist implemented? Or just the common referrer spam list?
