### ISSUE TITLE
Some URLs double up

### ISSUE THREAD

**Issue by bradders** [usefathom/fathom#155]
I've noticed that sometimes I see the same url twice, why is that?
<img width="348" alt="screenshot 2018-10-14 12 03 49" src="https://user-images.githubusercontent.com/840983/46920871-5fe3fe00-cfa9-11e8-9ffe-a38744f1f27d.png">

**Comment by m1guelpf** [comment]
Hover the URLs, you'll probably find host is different

**Comment by bradders** [comment]
@m1guelpf Good spot, that's exactly it! Thanks.
