### ISSUE TITLE
any chance to have static build for arm32 , arm64, x86 (32bit)

### ISSUE THREAD

**Issue by nephaste** [usefathom/fathom#158]
just built for Qnap NAS Fathom 

https://www.qnapclub.eu/fr/qpkg/648

unfortunately, static binary is available only for amd64

we also have armv5, armv7 , armv8 (64bit) and x86 (32bit)... i wonder if it is possible to get this built in release

**Comment by dannyvankooten** [comment]
Hi @nephaste,

9b6c102b74d86d9f599832c51a267f602a4683c9 adds static builds for linux/arm64 (armv8) and linux/386 which we'll be including in official releases from now on, but I'm afraid that's as far as we want to go with providing static binaries at this stage.

To support different platforms you'll need to build from source for now. This should be relatively easy to automate though, it's just not something that we have the time for to officially support at this stage in Fathom's life.
