### ISSUE TITLE
Keyboard navigation in latest version

### ISSUE THREAD

**Issue by bradders** [usefathom/fathom#161]
Did the latest version/update (multi-site) nuke or change the keyboard navigation shortcuts? Opt+arrow keys doesn't seem to work for me any more.

**Comment by dannyvankooten** [comment]
Hi @bradders, it uses just the arrow keys now. As ALT + arrow keys was a reserved key combination in Firefox. The text in the footer should reflect that.

**Comment by bradders** [comment]
@dannyvankooten Missed the updated footer text! I'm in Firefox, and the arrow keys don't work (works fine in Chrome, though).
