### ISSUE TITLE
Provide legal text

### ISSUE THREAD

**Issue by lgraubner** [usefathom/fathom#162]
I'm living in Germany and I'm required to offer a privacy notice. It's common for eg. Google Analytics to describe what the tracking does. Is it possible to add a standard text in the wiki to use?

<details><summary>Google Analytics example</summary>
<h3>Google Analytics</h3>
        <p>
          Google Analytics is a web analytics service offered by Google that
          tracks and reports website traffic. Google uses the data collected to
          track and monitor the use of our Service. This data is shared with
          other Google services. Google may use the collected data to
          contextualize and personalize the ads of its own advertising network.
        </p>
        <p>
          You can opt-out of having made your activity on the Service available
          to Google Analytics by installing the Google Analytics opt-out browser
          add-on. The add-on prevents the Google Analytics JavaScript (ga.js,
          analytics.js, and dc.js) from sharing information with Google
          Analytics about visits activity.
        </p>
        <p>
          For more information on the privacy practices of Google, please visit
          the Google Privacy & Terms web page:
            https://policies.google.com/privacy?hl=en
        </ü>
</summary>

**Comment by pjrvs** [comment]
Note, I am not a lawyer and this is not legal advice - here's a rough draft. @dannyvankooten anything to add?

### Fathom Analytics

Fathom Analytics is a website analytics service offered by ibericode BV that tracks and reports website traffic without compromising data or user privacy. Fathom does not use the data collected for anything other than to report to the customer directly on aggregate trends. Zero website visitor information is ever tracked, Fathom acknowledges "Do Not Track", and Fathom is GDPR compliant.

For more information, see our data collection policy: https://usefathom.com/data/

**Comment by lgraubner** [comment]
Thanks, sounds good. This is more suited to the hosted plans, right? Does it make sense to create another one for the self-hosted version? Can I help to add this to the wiki?

**Comment by dannyvankooten** [comment]
Looks good to me @pjrvs, but does it make sense to explain "Do Not Track" a bit more? Maybe like this?

---

### Fathom Analytics

Fathom Analytics is website analytics software that tracks and reports aggregate website traffic without compromising on your privacy. Fathom only reports on aggregates, so no information specific to the website visitor is ever tracked or recorded.

You can opt-out of tracking by the Fathom software by enabling "Do Not Track" in your browser settings.

**Comment by pjrvs** [comment]
That works for me!

**Comment by lgraubner** [comment]
Sadly I have no permission to add this to the wiki. Anyways thanks for your effort, this looks fine for me.
