### ISSUE TITLE
JS errors with appendChild and removeChild

### ISSUE THREAD

**Issue by msencenb** [usefathom/fathom#165]
This bug seems to be happening occasionally in my app, but not always, as I have data in my fathom dashboard. Using the hosted fathom pro service, here's a screenshot from my local environment:

![image](https://user-images.githubusercontent.com/220153/47187502-313b8f80-d2e9-11e8-8888-9a4187654901.png)

**Comment by dannyvankooten** [comment]
Hey @msencenb,

Did you add the tracking snippet to your `<head>` section?

My theory is that there is a race condition between the tracking script loading before your app has even initialized its `document.body`. 22121a8f051c49a9cb6c6c3916b06c4ddc332176 should prevent that from happening, I'm updating everyone on our hosted offering as we speak.

**Comment by msencenb** [comment]
Yes, you got it. Looks good now, thank you!
