### ISSUE TITLE
How to kill Fathom server process?

### ISSUE THREAD

**Issue by hendrasan** [usefathom/fathom#167]
I want to stop fathom server. I tried to kill the process in port 9000, but new fathom process keeps respawning. Is there any command to stop the fathom server process?

**Comment by dannyvankooten** [comment]
Hey @hendrasan,

Most likely you have Systemd configured to automatically respawn the process whenever it shuts down. To kill it entirely, you have to disable the service you configured.

Example using the [names in the wiki](https://github.com/usefathom/fathom/wiki/Running-Fathom-as-a-service):

```
sudo systemctl stop fathom
sudo systemctl disable fathom
```

**Comment by hendrasan** [comment]
I don't have systemd configured though.

I end up solving this by deleting/renaming the fathom in usr/local/bin
