### ISSUE TITLE
Omnibus package to simplify install?

### ISSUE THREAD

**Issue by Spone** [usefathom/fathom#168]
Hi there,

I had a look at the [installation instructions](https://github.com/usefathom/fathom/wiki/Installing-&-running-Fathom) for Fathom, and I feel like it's quite complicated to get it up and running.

Would you consider building an [Omnibus](https://github.com/chef/omnibus) package, like Gitlab [does](https://gitlab.com/gitlab-org/omnibus-gitlab/) for instance?
It makes install and update as easy as `apt install [package]`

Thanks in advance!

**Comment by dannyvankooten** [comment]
Hey @Spone,

I'm afraid that the process won't be that much easier using an Omnibus package but that it's mostly the installation instructions that could do with some improvements.

To run Fathom in its default state, all you need to is to downloda the binary to your server and then run it. It will then spin-up a webserver listening on port 9000 using a SQLite database in the current working directory.

So to get Fathom up & running quickly, the following will do:

```
wget https://github.com/usefathom/fathom/releases/download/latest-development/fathom-linux-amd64
chmod +x fathom-linux-amd64
./fathom-linux-amd64 server
```

That said, I haven't heard of Omnibus before and it definitely would be awesome if one could simply use `apt` to install & run Fathom. Does it manage Systemd services too?

**Comment by dannyvankooten** [comment]
Using version controlled files instead of GitHub's wiki is a great idea. I'll get that done!

**Comment by geerlingguy** [comment]
Also if you have Docker available, you can run for evaluation or even for production using Fathom's docker image: https://hub.docker.com/r/usefathom/fathom

    docker run -d -p 8080:8080 usefathom/fathom:latest

(Posting this because I just found this Docker image... after working on building one of my own then realizing there's already an 'official' version :P ).

**Comment by JackEllis** [comment]
@Spone Appreciate the feedback. We offer a [hosted version of Fathom](https://usefathom.com/) for users struggling to install. In addition, we've also put together a 1-click package over on Digital Ocean, which makes things very easy.
