### ISSUE TITLE
Nginx path error in wiki

### ISSUE THREAD

**Issue by Spone** [usefathom/fathom#169]
Hi there,

I think there's an error in this paragraph https://github.com/usefathom/fathom/wiki/Installing-&-running-Fathom#using-nginx-with-fathom

Instead of:

> Create a new file in `/etc/sites-enabled/my-fathom-site`

It should read:

> Create a new file in `/etc/nginx/sites-enabled/my-fathom-site`

Which is the default path in Nginx.

**Comment by dannyvankooten** [comment]
Hey, you're absolutely right. Nicely spotted, thanks for sharing!
