### ISSUE TITLE
Site switcher dropdown iOS

### ISSUE THREAD

**Issue by bradders** [usefathom/fathom#172]
The site switcher dropdown on iOS mobile seems a little buggy. Presuming as it relies on the hover states.

But clicking on the down arrow doesn't work, and when a site is selected the dropdown doesn't disappear. When choosing a site, then clicking the up arrow (so as to hide the sites) the top site is selected instead.

**Comment by dannyvankooten** [comment]
Related to #164.

What iOS browser are you seeing this in specificially @bradders?

**Comment by dannyvankooten** [comment]
Thanks @bradders, PR is merged, we'll be updating your Fathom dashboard on Monday!
