### ISSUE TITLE
[Firefox] Cannot use arrow keys to cycle through date ranges.

### ISSUE THREAD

**Issue by mhanberg** [usefathom/fathom#173]
```
Fathom version: 1.10
Firefox Developer edition version: 64.0b4
Firefox version: 63.0
```

The console reports the error

```
ReferenceError: event is not defined [Learn More] script.js:1:14632 
```

This line refers to this function

```javascript
{
  key: 'handleKeyPress',
  value: function (t) {
    var e = event.target.tagName;
    if ('INPUT' !== e && 'TEXTAREA' !== e) {
      var n,
        r,
        i = this.state.endDate - this.state.startDate + 1000;
      switch (t.keyCode) {
        case 37:
          n = new Date( + this.state.startDate - i),
            r = new Date( + this.state.endDate - i),
            this.setDateRange(n, r);
          break;
        case 39:
          n = new Date( + this.state.startDate + i),
            r = new Date( + this.state.endDate + i),
            this.setDateRange(n, r)
      }
    }
  }
}
```

It is complaining that the variable `event` is undefined. I am assuming that this is supposed to say `var e = t.target.tagName;`.

What is weird is that this exact same code appears in Safari (not trying to say they _should_ be different), but `event` is not undefined. In Safari, `event == t` evaluates to `true`.

**Comment by mhanberg** [comment]
This seems related to #160. Feel free to close if that should resolve this.

**Comment by dannyvankooten** [comment]
Hey @mhanberg,

Yeah, that was my first thought as well. We'll tag a new version later this week so that you can update by downloading one of the prebuilt releases!
