### ISSUE TITLE
Private public dashboards? 🤔

### ISSUE THREAD

**Issue by weavermedia** [usefathom/fathom#175]
It would cool if a public dashboard could also have simple password protection.

Might sound counter-intuitive but it would allow me to install and manage Fathom for a handful of clients from my own hosted account and give each of them access to only their public dashboard via a password.

They wouldn't get access to my hosted account - just the ability to view their 'public' (password protected) dashboard. This could also work in a similar way for internal teams.

Implementation would be simple - just add something like `dashboard_password` to `Site` but as a business decision I'm not sure this is something you would go for?

**Comment by m1guelpf** [comment]
For me, this opens a wider topic with permissions. Can I have some private sites and some public ones in a Fathom instance? How about making a site public when an user exists?

**Comment by dannyvankooten** [comment]
@weavermedia Would a user management feature where access is defined on a per-site basis help here? That way you should be able to set this up by adding multiple users, where each user only has access to 1 (or a subset of) site(s) within the dashboard.

@m1guelpf Hmm, we could eventually go there, but the issue is mostly that a public dashboard complicates things when it comes to showing site settings and the aforementioned user management feature, so I think that for now the plan is to keep public dashboards rather simple just to speed up development for other features and improvements.

**Comment by weavermedia** [comment]
@dannyvankooten Yes, user management would certainly solve this 👍

**Comment by austinginder** [comment]
+1 for user management. 

Would also be amazing if there would be some way to generate a one time login link via a Fathom API. The use case would be a integrating Fathom into a custom web hosting panel with a secured way to open up Fathom without needing a password.

**Comment by JackEllis** [comment]
@weavermedia We've amended our documentation to not support public dashboards anymore. The next version will reintroduce support for it. Also, coming back to what you said about giving access to your clients, Fathom PRO is going to be introducing more advanced user management in the next release :)

**Comment by benwiley4000** [comment]
@JackEllis Do you have an expected timeline for the next release? Public dashboards would be a killer feature to use. :)

**Comment by JackEllis** [comment]
@benwiley4000 Not sure on next release date here, Ben, but it'll include this for sure. No password for public dashboards though.

**Comment by benwiley4000** [comment]
No password is what I want! Thanks! Will there be anything early access like an alpha?

**Comment by JackEllis** [comment]
@benwiley4000 No alpha for OS, it'll just be a new release. We're working on this alongside a new version of [Fathom PRO](https://usefathom.com/) and our other commitments (unfortunately we're not full time on Fathom) :)
