### ISSUE TITLE
Static Site Question

### ISSUE THREAD

**Issue by bradders** [usefathom/fathom#177]
Not necessarily an issue, more a question.

I've got Fathom setup on a purely static site, HTML/CSS/JS (no backend) and my dashboard shows duplicate pages, as the full url is different.

Obviously this isn't a problem on other site where I use Fathom, as I include Fathom based on .env settings, so it's only tracking the live site.

Obvious fix to my problem is to use some sort of show/hide on my end to only include the tracking for the correct urls, but I wondered whether it was planned on locking down tracking on Fathom for only the named url.

**Comment by dannyvankooten** [comment]
Hey @bradders,

We might add some sort of whitelist in the future where Fathom will only accept data coming from that site, but it will be artificial at best as the hostname can easily be spoofed. 

Probably the most flexible is to use a slightly modified tracking snippet that uses JavaScript to determine whether to load the tracker / record the pageview. 

For example, you can wrap the entire snippet in `if( location.hostname === 'my.website.com' ) { ... }` to only have it load on **my.website.com**.

Here's an example:

```html
<!-- Fathom - simple website analytics - https://github.com/usefathom/fathom -->
<script>
if( location.hostname === 'my.website.com' ) {
	(function(f, a, t, h, o, m){
		a[h]=a[h]||function(){
			(a[h].q=a[h].q||[]).push(arguments)
		};
		o=f.createElement('script'),
		m=f.getElementsByTagName('script')[0];
		o.async=1; o.src=t; o.id='fathom-script';
		m.parentNode.insertBefore(o,m)
	})(document, window, '//danny.usesfathom.com/tracker.js', 'fathom');
	fathom('set', 'siteId', 'XXXXXXX');
	fathom('trackPageview');
}
</script>
<!-- / Fathom -->
```
