### ISSUE TITLE
Support Let's Encrypt

### ISSUE THREAD

**Issue by austinginder** [usefathom/fathom#18]
In order for this to be useable in the real world, Fathom needs to run over https. How about bundling in Let's Encrypt support. I'm not as familiar with Golang however it looks like some other projects might easily be plugged in like this one: https://github.com/gin-gonic/autotls. 

From the command line I could see it being used something like this.
`fathom server --webroot=./build --domain=<domain>`

If the domain flag is used then it could automatically setup Let's Encrypt and redirect to HTTPS for that particular domain.

**Comment by EduardoRT** [comment]
I'm using [træfik](https://traefik.io/) as a reverse proxy with the docker-compose file that's provided here with a few tweaks, træfik provides a nice way to have automatic HTTPS LE Cert creation and management – Just a FYI for anyone reading this.

**Comment by davidlowry** [comment]
A full working sample for Apache users of a reverse proxy. I've commented out the Lets Encrypt inserted code but you can uncomment if you already have the cert.

`<VirtualHost *:80>
ServerName fathom.domain.net
RewriteEngine on
RewriteCond %{SERVER_NAME} =fathom.domain.net
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

<IfModule mod_ssl.c>
    <VirtualHost server-ip:443>
        ServerName fathom.domain.net
        ProxyPreserveHost On
        ProxyPass / http://0.0.0.0:9000/
        ProxyPassReverse / http://0.0.0.0:9000/

        #Include /etc/letsencrypt/options-ssl-apache.conf
        #SSLCertificateFile /etc/letsencrypt/live/fathom.domain.net/cert.pem
        #SSLCertificateKeyFile /etc/letsencrypt/live/fathom.domain.net/privkey.pem
        #SSLCertificateChainFile /etc/letsencrypt/live/fathom.domain.net/chain.pem
    </VirtualHost>
</IfModule>`

**Comment by o1ek** [comment]
Caddy has the simplest config. You can just point your subdomain to server IP and run something like it:
```
DOMAIN=fathom.example.com

cat <<EOF > Caddyfile
$DOMAIN {
proxy / 127.0.0.1:8080 {
        transparent
}
}
EOF

docker run -d --name caddy \
    --restart unless-stopped --net=host \
    -v $(pwd)/Caddyfile:/etc/caddy/Caddyfile \
    -v $(pwd)/certs:/root/.caddy \
    -p 80:80 -p 443:443 \
    ubox/caddy
```

**Comment by EduardoRT** [comment]
I loved Caddy, but they charge $25/month per "instance" and they count local-dev as an instance too, taken from their FAQs

`The commercial license grants the right to use Caddy in a commercial context based on how many instances you run or how many employees will be using Caddy ("users") at any given time. An instance is an OS process of Caddy. For example, if you have 2 instances of Caddy in production and 3 web developers using Caddy locally to build your website, that's 5 instances. (A single developer who starts multiple instances of Caddy temporarily in local dev can still just count as 1.) If you also spin up a maximum of 3 containers at a time with Caddy binaries inside it, that's a total of 8 instances. If you distribute Caddy to others, contact us for distributor pricing.`

[Caddy Pricing](https://caddyserver.com/products/licenses)

I don't discourage anyone to use Caddy, it's a great product – I'm just giving a heads-up about this in case of the project your using it on happens to make money.

**Comment by thangngoc89** [comment]
@EduardoRT you can build from source and use it for commercial purposes. The pricing applies to official binary build

**Comment by EduardoRT** [comment]
@thangngoc89 that's really cool! I'll reconsider Caddy instead of nginx for my containers then!

**Comment by jhabdas** [comment]
Automatic LE cert renewals is a big draw for Caddy. Unfortunately Caddy is [not _libre_ software](https://caddyserver.com/products/licenses) whereas [Traefik](https://github.com/containous/traefik/) is. That said both provide automatic LE cert renewals and serve different purposes.

**Comment by jhabdas** [comment]
@thangngoc89 what do you suppose would happen if someone, for instance, decided copied their Apache-licensed source code and automatically produced an _unofficial_ binary for each release?

**Comment by jhabdas** [comment]
@thangngoc89 what do you suppose would happen if someone, for instance, chose to copy their Apache-licensed source code and automatically produced an _unofficial_ binary for each release?

**Comment by thangngoc89** [comment]
@jhabdas don’t ask me, I have no ideas. The official binary is liscensed different from the source code (which is apache 2.0) 

See https://caddyserver.com/products/licenses 

INAL but it roughly means that if you compiles it from source, you are freely to use it as long as you follow the apache 2.0 license. And you do need to compile from source if you want a custm plugin or you write a plugin anyway.
