### ISSUE TITLE
Export/Import data

### ISSUE THREAD

**Issue by m1guelpf** [usefathom/fathom#183]
Whenever I have to move data to a new instance, I have to go into the volume, copy the db go into the new volume and replace it (I'm using Docker). Can we have some way to import and export data via the dashboard, even if it's just downloading/uploading the db?

**Comment by dannyvankooten** [comment]
Yes, this is already on the [roadmap](https://trello.com/b/x2aBwH2J/fathom-roadmap). Please vote for it if you haven't do so already as we use that to gauge popularity when determining where to focus our efforts.
