### ISSUE TITLE
Stuck on "Add a new site to track"

### ISSUE THREAD

**Issue by jamesponddotco** [usefathom/fathom#187]
Hi,

I just added Fathom to a new server and it seems I am stuck on the "Add a new site to track with Fathom" pop-up screen. Server is running Fathom version 1.2.0, which is behind NGINX 1.15.6.

When accessing the URL I set for Fathom, I input my credentials and said pop-up shows up. I input my domain, click on "Create site" and nothing happens. If I press ESC to close the pop-up, it shows up again once I reload the page.

Tested with GNOME Web and Firefox. No error shows up on Firefox's Console or on NGINX's error logs.

Weirdly enough, it does work on my local machine with the exact same NGINX configuration files. The only difference is that the local version was upgraded from version 1.0, while the production version went directly to 1.2.

The only other difference I can think of is that the local version uses a small secret with no special characters while the production versions uses a 64 characters secret with special characters (excluding quotes and the likes).

Happy to provide other information if necessary.

**Comment by jamesponddotco** [comment]
Found this on `/var/log/syslog`:

`level=error msg="error handling reques      t" error="attempt to write a readonly database" request="POST /api/sites"`

The owner for the `.env` and `fathom.db` files is `www-data`, but changing it to `root` does not change anything.

**Comment by dannyvankooten** [comment]
Hi @jamesponddotco,

That must be it. The site is never really created because Fathom can’t write to the database.

Can you check as which user the ‘fathom server’ process is running and make sure it matches the owner of the SQLite database file? 

Alternatively, is any other process interacting with the database file at the same time?

**Comment by dannyvankooten** [comment]
By the way, closing this issue as it is not specific to Fathom, but due to your set-up. Also, please note that after changing the file permissions on the database file you'll have to restart your Fathom process for the changes to take effect.
