### ISSUE TITLE
[Question] Ublock origin/Do Not Track 

### ISSUE THREAD

**Issue by nkvname** [usefathom/fathom#189]
Hi! 

Simple question. Does fathom gets blocked by Ublock origin, Do Not track by Mozilla and other similar solutions?

**Comment by dannyvankooten** [comment]
Hi @nkvname,

Fathom respects "Do Not Track" in your browser setting (so not just for Mozilla), so it won't collect any stats from people with that setting enabled.

Fathom is not currently on any of the uBlock list sources, so at the time of writing it's not blocked by uBlock (using the default settings).
