### ISSUE TITLE
latest-development release out of date

### ISSUE THREAD

**Issue by samuelmeuli** [usefathom/fathom#191]
Hi @dannyvankooten,

The download URL (https://github.com/usefathom/fathom/releases/download/latest-development/fathom-linux-amd64) in the installation and update instructions seems to be out of date:

```sh
$ fathom --version
Fathom version 1.1.0
```

It would be great if you could update the `latest-development` release with the latest binaries. Thanks! :)

**Comment by dannyvankooten** [comment]
Hi @samuelmeuli,

Please switch your usage over to the more stable https://github.com/usefathom/fathom/releases/latest release, as we're about to stop providing regular development builds.

We'll tag releases often enough for this to not really matter though.  :)
