### ISSUE TITLE
Contribution guidelines?

### ISSUE THREAD

**Issue by hypesystem** [usefathom/fathom#192]
Hey! Great project!

I was wondering what the correct approach for contributing code would be?

In particular I saw that an API is planned. I would love to find a way to help out :-)

What should my first step be?

**Comment by dannyvankooten** [comment]
Hey @hypesystem,

We don't have any particular system in place yet, but I'd say opening this issue to discuss a certain feature / bug / aspect you'd like to contribute to is a great first step!

Relating the API; the current dashboard is already fully decoupled from the server-side API so basically the only real thing that is needed is an authentication mechanism (besides the current session-based approach) and probably some interface code to manage API keys. But if you have any thoughts or ideas on how you think this should ideally work, then I'd love to hear it!

**Comment by Carlows** [comment]
I would also love to contribute to this project, having a CONTRIBUTING file describing key parts of the code would be nice. 

Regarding tracking what devices users are using in your website, or maybe only device resolutions and aggregating them in a table, how problematic would be to achieve that?
