### ISSUE TITLE
Index page not found

### ISSUE THREAD

**Issue by phil-opp** [usefathom/fathom#193]
Hi, I'm trying to get fathom working on a new platform, but I keep getting 404 errors for the index page:

![image](https://user-images.githubusercontent.com/1131315/49697868-d9205b80-fbbc-11e8-8caf-f3773d0f966d.png)

Interestingly all other URLs seem to work fine (e.g. favicon, css, fonts), only the `/` or `index.html` is not found.

The output from running `fathom` is:

```
INFO[0002] ::1 - - [09/Dec/2018:13:11:58 +0000] "GET /index.html HTTP/1.1" 404 566 
INFO[0002] ::1 - - [09/Dec/2018:13:11:59 +0000] "GET /assets/img/favicon.png HTTP/1.1" 200 998 
INFO[0002] ::1 - - [09/Dec/2018:13:11:59 +0000] "GET /assets/css/styles.css?t=1543569696963 HTTP/1.1" 200 23088 
INFO[0002] ::1 - - [09/Dec/2018:13:11:59 +0000] "GET /assets/fonts/overpass-light.woff2 HTTP/1.1" 200 34472 
INFO[0002] ::1 - - [09/Dec/2018:13:11:59 +0000] "GET /assets/fonts/overpass-bold.woff2 HTTP/1.1" 200 34752
```

I tried both fathom-1.1.1 and fathom-1.2.1. What am I doing wrong?

**Comment by fheidenreich** [comment]
I had a similar issue and it was driving me nuts. Rewriting index.html to / did the trick for me.

```
location ~ {
	rewrite "^/index\.html$" / break;
	proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Forwarded-For $remote_addr;
	proxy_set_header Host $host;
	proxy_pass http://127.0.0.1:9000;
}
```
