### ISSUE TITLE
Ignore fbclid parameter

### ISSUE THREAD

**Issue by ridercz** [usefathom/fathom#194]
Facebook started to add the 'fbclid' parameter which messes up the stats. It would be nice if Fathom could either use (I don't know what it's good for) or ignore.

**Comment by dannyvankooten** [comment]
Hey @ridercz,

A better solution would probably be for your site to properly define a canonical URL for each of your pages. If a `<link rel="canonical" href="https://example.com/dresses/green-dresses" />` is present in your page mark-up, Fathom will use that to consolidate URL's.

**Comment by cweagans** [comment]
Came here to open this exact issue. Thanks for the solution, @dannyvankooten!
