### ISSUE TITLE
Initial migration fails in MySQL because Specified key was too long

### ISSUE THREAD

**Issue by phillbailey** [usefathom/fathom#198]
Hi,

This appears to be the same issue that was dealt with in #56 however the fix that was added there appears now not to be working.

I have installed and configured fathom with a user. Adding the user returned the error "Specified key was too long; max key length is 1000 bytes", which I have tracked down to the following [line of migration code, line 54 of 1_initial_tables.sql](https://github.com/usefathom/fathom/blob/master/pkg/datastore/sqlstore/migrations/mysql/1_initial_tables.sql#L54), which creates the index on the daily_page_stats table. 

I have dropped the database tables and recreated them using the SQL from the linked file, but the error still occurs on line 54. I have confirmed that the daily_page_stats table is using the MyISAM engine and that the encoding is set to utf8_general_ci. I have also tried reducing the length of the hostname and pathname fields, but even if I set them to 190 characters (less than the 191 mentioned in the previous issue), creating the index still fails.

I'm using the newest available version of MariaDB (10.0.36) on Ubuntu 16.04.5 LTS. 

Is there anything else I can try or am I better just using sqlite?

Thank you,

Phill

**Comment by dannyvankooten** [comment]
Hey @phillbailey,

Nice catch - somehow it seems that your installation has MyISAM defined as the default table storage engine causing this issue to show up. We're now explicitly telling MySQL to use INNODB instead.
