### ISSUE TITLE
Error connecting to database: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work.

### ISSUE THREAD

**Issue by psudoorg** [usefathom/fathom#200]
Facing this error -
**FATA[0000] Error connecting to database: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub** after following the steps as mentioned here - https://github.com/usefathom/fathom/blob/master/docs/Installation%20instructions.md

```
[ec2-user@ip-172-31-27-171 ~]$ cd ~/stats
[ec2-user@ip-172-31-27-171 stats]$ fathom server
INFO[0000] Fathom version 1.2.1, commit 8f7c6d2e45ebb28651208e2a7320e29948ecdb2c, built at 2018-11-30T09:21:37Z 
INFO[0000] Configuration file: /home/ec2-user/stats/.env 
FATA[0000] Error connecting to database: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub 
[ec2-user@ip-172-31-27-171 stats]$ 
```

Please advise as to what's going wrong? I've also not done anything towards the `optional` steps.

**Comment by dannyvankooten** [comment]
Hi @psudoorg,

What OS are you on and are you sure you downloaded the correct binary for your operating system?

**Comment by minthemiddle** [comment]
Exactly the same problem here.
Downloaded `fathom_1.2.1_linux_386.tar.gz` on `Ubuntu 18.04.1 LTS` which is `x86_64`.

**Comment by dannyvankooten** [comment]
Hi @minthemiddle,

Does the issue persist if you go for the 64-bit version (which I think should be the correct binary for your system): https://github.com/usefathom/fathom/releases/download/v1.2.1/fathom_1.2.1_linux_amd64.tar.gz?

**Comment by coreymcc** [comment]
Hi, Danny. I had the exact same problem as minthemiddle when I tried fathom_1.2.1_linux_386.tar.gz. 

I saw your suggestion to try the amd64 release instead. However, now I am getting this error: "bash: /usr/local/bin/fathom: cannot execute binary file"

My arch is also x86_64. However, I am trying to run this on a CentOS 7 system, whereas minthemiddle got it working on Ubuntu. Is there something else I should try? Thanks!

**Comment by coreymcc** [comment]
P.S. Before I found this thread, I assumed that the issue was that I needed to install Golang as a prerequisite to get cgo, which I did using yum. (go version go1.11.5 linux/amd64). However, it appears that Golang isn't actually required if the fathom binary is correct for my system, right? Thanks again.

**Comment by coreymcc** [comment]
I realized now that this issue closed, and there's a related issue tagged "next release" for fixing this. In the meantime, I got it working by compiling the source for the 1.2.1 tag, so I think I'm all set for now. Thanks!
