### ISSUE TITLE
Site ID of deleted site is reused

### ISSUE THREAD

**Issue by samuelmeuli** [usefathom/fathom#202]
Hi @dannyvankooten,

I've recently deleted a site from the Fathom dashboard and just added a new one. Unfortunately, after generating the tracking code for the new site, all analytics data from the previously deleted site now appears under the new website.

Looking at the database, it seems that when adding a site, it is assigned the same `id` as the deleted site, thus linking it to the corresponding data.

**Comment by JackEllis** [comment]
@samuelmeuli A workaround for this one would be to open the SQLite database up, and clear out all the analytics data before the date you created the new one. Appreciate the bug is still there but this would bypass that issue for now.
