### ISSUE TITLE
Fathom tracks visitors from other domains

### ISSUE THREAD

**Issue by ovalseven8** [usefathom/fathom#204]
Let's say I have a Fathom instance for the website `www.my-website.com`.

So, I paste the Fathom code (script) to all my pages on this website so that Fathom can track the number of visitors. Unfortunately, I've found out that everybody **could** paste this snippet into his website and Fathom counts those requests, which means they can manipulate my stats.

So, it would be cool if Fathom only counts the visitors that load the script from my website and not from another domain. So that when you create a new website, that you not only have to provide the name, but also the host for which the tracking is active.

E.g. with `my-website.com` I want to track all requests to this host. Or with `*.my-website.com` I also track the visits to the subdomains. However, it would not be possible for others to include the script and manipulate my stats.

**Comment by dannyvankooten** [comment]
Hey @ovalseven8,

I agree that this would be cool and we'd like to add it one day, but it's pretty low priority right now as it is not really offering any protection. A hostname is easily spoofed, and even copying someone else's Google Analytics snippet will allow me to send traffic to their GA dashboard.

That said, I'd like to solve this one day by providing filters so that you can filter out certain pageviews on an indefinite basis, much like how GA attempts to tackle this.

**Comment by chaoxu** [comment]
I host my site on github, so people sometimes fork but do not remove my tracking code. 

If we assume the person copying your code is not malicious, here is a quick fix in the javascript.

```
  if(window.location.hostname === "yourhostname.com"){
    // Your fathom tracking code. 
  }
```

**Comment by JackEllis** [comment]
No plans to build this into script at present because, as Danny said, it's super easy to spoof.

**Comment by rhysperry111** [comment]
Sorry for bumping this thread, but even if it's super easy to spoof then it's ok. Most of the times I get random records it's from innocent people. Not everyone is doing things for malicious reasons.
Sorry for the mini-rant.

**Comment by JackEllis** [comment]
@rhysperry111 I don’t understand what you’re saying here

**Comment by rhysperry111** [comment]
I'm actually so sorry. Didn't read the previous comments and I was just a little annoyed because I have discovered my analytics metrics have been messed up by someone who copied my code.
