### ISSUE TITLE
How do I exclude / ignore my traffic from Fathom?

### ISSUE THREAD

**Issue by minthemiddle** [usefathom/fathom#206]
What's the easiest and most stable way to exclude / ignore my traffic from Fathom?

**Comment by dannyvankooten** [comment]
@minthemiddle There are several ways to stop Fathom from tracking a certain pageview:

- Enable "Do Not Track" in your browser settings. Fathom respects this setting.
- Only add the tracking snippet to your page when a certain condition evaluates to true. You could for example use this to only print the snippet when the site is loaded from a certain domain (and thus exclude your development environment). 

We'd like to support filters one day, where you can filter out traffic from certain IP addresses / ranges but right now we don't offer anything like that yet, sorry.

**Comment by Alanaktion** [comment]
Until this is implemented in Fathom directly, you can use your server configuration to block certain IPs from accessing the `/collect` path. For example in nginx:

```
location / {
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host $host;
    proxy_pass http://127.0.0.1:9000;
    location /collect {
        deny 1.2.3.4; # Add multiple `deny` lines here for each IP to block
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_pass http://127.0.0.1:9000;
    }
}
```

As long as you only block the `/collect` path, the admin view is still completely usable from that IP, and it only blocks the actual analytics collection. This should work nicely with no side effects.

**Comment by mxmzb** [comment]
I am not sure, but when I enable "DNT" in my Chrome (Canary), I am still being shown in the fathom dashboard. Is that supposed to work like this?

**Comment by JackEllis** [comment]
@mxmzb DNT is listened to with Lite but not listened to in Pro. This is because DNT has been abandoned and also because DNT is to do with user specific preferences. Fathom does not track individual users.

**Comment by mxmzb** [comment]
Thanks for answering (I am on Pro version btw). This means there is no way to exclude myself from the stats though on my production site?

I am asking because I'd like to make a comparison with GA and I'd like to not influence the stats by including my arbitrary actions into the stats.

Thank you for your help!

**Comment by MrOggy85** [comment]
I am using caddy and this is my config:
```
monitor.example.com {
  @myself remote_ip MY_IP
  handle @myself {
    abort /collect
    reverse_proxy http://fathom:8080
  }

  reverse_proxy http://fathom:8080
}
```
This will _handle_ your specified IP and abort any requests to `/collect`, but still let you access the dashboard.
