### ISSUE TITLE
macOS Build/Installation Instructions

### ISSUE THREAD

**Issue by jafish** [usefathom/fathom#210]
Can you provide instructions for running fathom on a macOS server? Is the BSD version compatible? Or are we advised to use Docker?

**Comment by bobbykjack** [comment]
I've managed to build it from source on macOS Mojave. Setting up the paths for the go libraries was the only really awkward bit. Let me know if you have any specific questions, especially if you decide to give it a go!

**Comment by JackEllis** [comment]
This isn't something I've got experience with. If someone else writes instructions, please submit a PR and we'll merge it
