### ISSUE TITLE
fathom nginx proxy

### ISSUE THREAD

**Issue by valsha** [usefathom/fathom#212]
Good day, just install fathom behind nginx reverse proxy (101.114.xxx.xxx), fathom logs (terminal) i can see all user activity and all user ip addresses is my nginx reverse proxy.

```
INFO[159452] 101.114.xxx.xxx - - [29/Jan/2019:14:03:45 +0000] "GET /api/sites/1/stats/site/realtime HTTP/1.0" 200 11
INFO[159463] 101.114.xxx.xxx - - [29/Jan/2019:14:03:56 +0000] "GET /accretian-auction-services/16937-trade-item-yuk.html?mode=hybrid HTTP/1.0" 404 566
INFO[159468] 101.114.xxx.xxx - - [29/Jan/2019:14:04:01 +0000] "GET /api/sites/1/stats/site/realtime HTTP/1.0" 200 11
INFO[159475] 101.114.xxx.xxx - - [29/Jan/2019:14:04:08 +0000] "GET /158438-post10.html HTTP/1.0" 404 566
```

I my nginx config is:

```
server {
	server_name stat.site.com;

	location / {
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $remote_addr;
		proxy_set_header Host $host;
		proxy_pass http://real_ipv4_address:9000; 
	}
}
```

**Comment by megalithic** [comment]
so what exactly is the issue you're describing?

**Comment by valsha** [comment]
fathom can't see REAL users IPs.

**Comment by shreyasminocha** [comment]
@valsha I think that's a feature, not a bug.

**Comment by dannyvankooten** [comment]
Hi @valsha,

Fathom doesn't rely on the user IP address so this is not a problem. Besides, you're passing the real IP address in the `X-Real-IP` header so Fathom can definitely access it if it wants to (but it doesn't).

**Comment by jhabdas** [comment]
IP addresses [_may not_ be](https://arstechnica.com/tech-policy/2016/10/eu-dynamic-static-ip-personal-data/) considered personal data (yet). Nevertheless, the less identifiers you store the better off you are—[unless you're name is Posteo](https://www.zdnet.com/article/log-free-email-provider-posteo-you-must-log-user-ip-addresses-court-rules/) and you're already dropping IPs at a DMZ outside the firewall.
