### ISSUE TITLE
How to deploy https?

### ISSUE THREAD

**Issue by chaoxu** [usefathom/fathom#213]
I'm a novice on actually getting things running. All I did is following the readme.
If I deploy fathom, I can only access it from http. 
Is there a tutorial to deploy it in https? My website is in https and can't use fathom if it is through http.

**Comment by jhabdas** [comment]
You need to [enable SSL on the server](https://github.com/usefathom/fathom/issues/93#issuecomment-404462722).

**Comment by dannyvankooten** [comment]
Hi @chaoxu,

Check out the bottom of the [installation instructions document](https://github.com/usefathom/fathom/blob/master/docs/Installation%20instructions.md#ssl-certificate), adding a SSL certificate to your Fathom dashboard should be relatively straightforward if you use LetsEncrypt.
