### ISSUE TITLE
dokku deployment

### ISSUE THREAD

**Issue by fi0** [usefathom/fathom#214]
how do I deploy it on dokku?

**Comment by johnfraney** [comment]
@fi0 You can use a [Dockerfile deployment](http://dokku.viewdocs.io/dokku/deployment/methods/dockerfiles/) and place the Fathom database in a [persistent storage volume](http://dokku.viewdocs.io/dokku/advanced-usage/persistent-storage/).

Here's the Dockerfile I use to do this:

```dockerfile
FROM usefathom/fathom:version-1.2.1

CMD ["./fathom", "server"]
```

You could also do a [Docker image deployment](http://dokku.viewdocs.io/dokku/deployment/methods/images/#deploying-from-a-docker-registry), although I'm less familiar with that method.

**Comment by gubler** [comment]
@johnfraney Thanks for the Dockerfile. Is there anything else you did to get Fathom up and running on Dokku? I pushed the Dockerfile and setup the DB in persistent storage like you explained and Dokku says its serving the site on 8080, but I'm not able to access the site. If I enter the container, it _does_ say Fathom is running.

- Is there some Nginx config that needs to be done?
- How did you handle SSL? Did you use Dokku's LetsEncrypt plugin?

Again, thank you for the information so far. Its further than I got on my own.

**Comment by johnfraney** [comment]
@gubler Ah! If that's the case I probably mapped that port to port 80. I'm not at my computer, but the Dokku docs detail how to map a port from the container to the host.

**Comment by JonathanMH** [comment]
> I did use the Let's Encrypt plugin, too. I can't recall if I mapped that port manually or if the plugin did it automatically.

In my experience the port is mapped by the letsencrypt plugin after deploying the app for the first time, then enabling the plugin. However if you're running into trouble you can always verify it actually did with: `dokku proxy:report`

**Comment by gubler** [comment]
@johnfraney Adding the proxy fixed the issue, and also allowed the Let's Encrypt plugin to work.

Thank you very much!
