### ISSUE TITLE
Adding more than one site?

### ISSUE THREAD

**Issue by geerlingguy** [usefathom/fathom#215]
Maybe I'm completely missing something, or maybe it's just Safari or something... but I can't seem to find a way to add another site to my installation—it seems like it just lets me add one initial site, and that's it.

I was excited to start using Fathom, but if I'm going to have to maintain an instance for all of my smaller sites I don't think I have the stomach for that.

It _looks_ like https://github.com/usefathom/fathom/issues/50 was created for this purpose... and there was a pull request merged (https://github.com/usefathom/fathom/pull/145), but using version 1.2.1 (latest stable release) I'm just not seeing it:

<img width="1170" alt="screen shot 2019-02-01 at 9 16 25 pm" src="https://user-images.githubusercontent.com/481677/52159247-fd516380-2666-11e9-8c4b-47ceae0d08fd.png">

**Comment by JackEllis** [comment]
Thanks for the write up @geerlingguy. The limitations for a non-authenticated user is a done on purpose, because in most cases the user will be securing their analytics and should create an admin user. With your second point, you are right, I've modified the docs.
