### ISSUE TITLE
Can't bookmark a specific site/view/date range

### ISSUE THREAD

**Issue by geerlingguy** [usefathom/fathom#217]
When I'm clicking around in the interface to find a specific date range I want to store (for later reference), or when I switch to another domain (e.g. I have two sites and am on the 2nd one in the list), the URL is always `/#!1w`.

So... because of that there's no way for me to get back to where I was without repeating all the UI clicks and actions.

Is this broken, or just not implemented yet (e.g. updating the url or url fragments as I click around in the UI... so like when I switch to another domain the URL would be `/#!1w&site=domaintwo.com`)?

**Comment by dannyvankooten** [comment]
Can confirm, this is broken right now.
