### ISSUE TITLE
Add server side log processing?

### ISSUE THREAD

**Issue by justinclift** [usefathom/fathom#219]
Fathom looks interesting, however it doesn't seem to have any ability to process server logs (eg Nginx access.log).

Is that something that's planned for later?

**Comment by JackEllis** [comment]
Hi @justinclift,

No plans for this. What are your reasons for wanting this?

Thanks!

**Comment by justinclift** [comment]
Javascript based log processing isn't able to detect page hits from clients that doesn't process it.

This would fix that problem.

**Comment by JackEllis** [comment]
@justinclift Good point! I think the solution here is to add a <noscript> to the embed code and that would hit the image to track a pageview. I'll add it to our roadmap!

**Comment by justinclift** [comment]
Interesting approach.  Sounds feasible. :smile:

**Comment by bridgestew** [comment]
For anyone who has to use a GDRP consent capture, the image tag (non-javascript) approach might require including a brief disclaimer/word of warning. I don't have a full breadth of knowledge on how getting consent for site analytics cookies work, but the solution with which I am most familiar is a Javascript implementation. 

How that solution works: 

- A script tag is added to the site for the analytics tracking but labeled as type="text/plain"
- When the visitor agrees to accept analytics cookies, the type is altered to "text/javascript" and then fires.
- The consent log is updated to capture the visitors consent to this type of cookie.

There is nothing wrong with having the <noscript> approach. I'm merely recommending that if it gets implemented as a feature, that some explanation for when _not_ to use the noscript image tag is mention for the sake of being very clear.

Hope that information is helpful. :)

**Comment by justinclift** [comment]
Interesting approach. :smile:
