### ISSUE TITLE
Domain showing in page names

### ISSUE THREAD

**Issue by austinginder** [usefathom/fathom#22]
For some reason most of my pages are including my domain in the page name as shown below. That is causing broken links as the the pages don't actually exist at domain.com/domain.com/. Maybe has something to do with WordPress' trailing slash: [https://anchor.host/blog/](https://anchor.host/blog/).

<img width="1345" alt="screen shot 2018-05-02 at 9 58 53 pm" src="https://user-images.githubusercontent.com/110346/39557229-0f3aff48-4e54-11e8-8f47-276a575e3db5.png">

**Comment by dannyvankooten** [comment]
Hey, woah, you're running this live. That is awesome! :tada: Hope you don't mind all the moving around I'm doing these weeks.

Just confirmed this to be a bug in the tracking script, should be fixed in latest master.

**Comment by dannyvankooten** [comment]
PS. While this change fixes it for new pageviews, it does not for your current (historical) pageviews. Running the following SQL query should resolve it.

```sql
ALTER TABLE pages UPDATE path = REPLACE(path, "anchost.host/", "/");
```

**Comment by austinginder** [comment]
Yeah call me adventurous. The data isn't important. I sorta figured I'll be purging and starting fresh a few times while it's under development. That said I ended up running the following to fix my data.

```sql
UPDATE pages SET path = REPLACE(path, 'anchor.host/', '/') WHERE path LIKE '%anchor.host%';
UPDATE pages SET path = REPLACE(path, '//', '/') WHERE path LIKE '%//%';
```
Also noticed a few double entries which I'm sure is getting the data dirty with the other relationships.
```sql 
select path, COUNT(*) c FROM pages GROUP BY path HAVING c > 1;
+------------------------------------+---+
| path                               | c |
+------------------------------------+---+
| /                                  | 2 |
| /combining-multiple-sql-files/     | 2 |
| /extracting-a-site-from-multisite/ | 2 |
+------------------------------------+---+
3 rows in set (0.00 sec)
```

I suspect at some point there should be some built in database housecleaning process which loops through duplicate page names and combines by reassigned pageviews/visitors and purging extras.
