### ISSUE TITLE
Missing Today (1d) view option

### ISSUE THREAD

**Issue by jackbaty** [usefathom/fathom#220]
I don't seem to have a "1d" option available.

My installation of 1.2.1 (Ubuntu 18.0.4 behind nginx)...

![2019-02-08-fathombaty](https://user-images.githubusercontent.com/970/52483885-f2289700-2b82-11e9-8a58-c45a556a6d55.png)

The usefathom.com example site...

![2019-02-08-fathom1d](https://user-images.githubusercontent.com/970/52483763-ad9cfb80-2b82-11e9-8a5d-8d4e30044c44.png)

Am I missing a configuration option somewhere?

Thanks

**Comment by bobbykjack** [comment]
Looks like that version doesn't include this commit, which is the key difference:

e2fb3aa9424967d3e37b155ae217aee160657f1d

**Comment by jackbaty** [comment]
Ah, that was it. I just rebuilt from latest and there it is, thanks!
