### ISSUE TITLE
Certbot command in the install instructions doesn't work

### ISSUE THREAD

**Issue by danieldunderfelt** [usefathom/fathom#227]
I got Fathom installed on a fresh Ubuntu 18.04 server with nginx and everything seems to be working fine. But when it came to obtaining a LetsEncrypt certificate the instructions failed me. Here's one of the errors I got while trying to get it to work:

```
Failed authorization procedure. example.domain (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://example.domain/.well-known/acme-challenge/loremipsum: "<html>\r\n<head><title>404 Not Found</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>404 Not Found</h1></center>\r\n<hr><center>"
```

So as far as I can tell it's not seeing the challenge things on the server. I've tried making a root and adding a location block for .well-known to nginx but to no avail. Do I just need to go full manual with certbot?

**Comment by JackEllis** [comment]
@danieldunderfelt I hope you got this sorted. This is outside of the scope for the kind of support here, since certbot works perfectly on 18.04. If you're installing on Digital Ocean, you can use the 1-click app we have now.

**Comment by danieldunderfelt** [comment]
I would agree, but you do provide instructions that don't work which is what the issue is about. I got my certificate with manual mode.
