### ISSUE TITLE
Frequent Segfaults

### ISSUE THREAD

**Issue by BlackCetha** [usefathom/fathom#229]
My installation of fathom frequently experiences segfaults when viewing the dashboard.
From my first read-through and limited knowledge in Go, it seems to stem from the MySQL-driver.

A full stacktrace is available here: https://gist.github.com/BlackCetha/91e74c2247329c171025dbdf9e6921a5

**Comment by JackEllis** [comment]
I'm not sure what's going on here either. If anyone else sees this and knows, please feel free to reply :)

**Comment by christopher-dG** [comment]
I ran into this too. Probably best to leave issues open if they're not resolved...

**Comment by JackEllis** [comment]
@christopher-dG How did you fix it? We can't re-create

**Comment by christopher-dG** [comment]
I haven't fixed anything, I just restarted it with systemd a few times until it worked. If it happens more I'll probably switch to sqlite since apparently it's not having that issue.

**Comment by JackEllis** [comment]
@christopher-dG Yeah, we don't recommend the mySQL driver for this. We may nuke it in the next release. Thanks for the details, I appreciate it.

**Comment by christopher-dG** [comment]
I'm using Postgres, so it seems like it's not just mysql 😦.

**Comment by JackEllis** [comment]
Sorry, anything outside of SQLIte
