### ISSUE TITLE
Remove DNT related code because it can be used for fingerprinting?

### ISSUE THREAD

**Issue by myobie** [usefathom/fathom#230]
[Webkit has stopped sending DNT headers](https://developer.apple.com/documentation/safari_release_notes/safari_12_1_release_notes#3130299) and it can be used for fingerprinting.

Also, the DNT recommendation has been [closed by the working group](https://github.com/w3c/dnt/commit/5d85d6c3d116b5eb29fddc69352a77d87dfd2310) with the note:

> ...there has not been sufficient deployment of these extensions (as defined) to justify further advancement, nor have there been indications of planned support among user agents, third parties, and the ecosystem at large.

Does it make sense to remove all DNT related code or are there other plans for fathom?

**Comment by JackEllis** [comment]
@myobie This is being considered. I'm going to close it for now but, behind the scenes, we've been debating what DNT means and what correctly honouring it looks like. To me (at present), the DNT specification defines tracking as:

> **Tracking** is the collection of data regarding a particular user's activity across multiple distinct contexts and the retention, use, or sharing of data derived from that activity outside the context in which it occurred. A context is a set of resources that are controlled by the same party or jointly controlled by a set of parties.

So the way I see this working would be to track the page view / visit (in aggregate) but, perhaps, not the page / referrer information. That way it still adds to the total stats. We're still deliberating this though, so please don't take my current thoughts as our next step.
