### ISSUE TITLE
Use navigator.sendBeacon over image tags

### ISSUE THREAD

**Issue by xPaw** [usefathom/fathom#231]
There's a good explainer here: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon#Description

**Comment by jhabdas** [comment]
open issue against chromium re: this method and csp: https://bugs.chromium.org/p/chromium/issues/detail?id=372197

**Comment by JackEllis** [comment]
@xPaw The compatibility isn't that great all round so we'd need to have some sort of sendBecaon with a fallback of image tag loading. The appealing piece about sendBeacon is that we can also attempt to track the exact moment they leave the website, leading to more accurate durations.

**Comment by xPaw** [comment]
All browsers except for IE support it (86% global): https://caniuse.com/#feat=beacon

But yes, a fallback to image can be kept if sendBeacon is not available.

**Comment by JackEllis** [comment]
No plans for modification in Fathom Lite.
