### ISSUE TITLE
PORT for postgresql config

### ISSUE THREAD

**Issue by dhuckins** [usefathom/fathom#232]
Looks like `Port` is missing from both the mysql adn postgres config, would it be possible to add it? (seems like a simple enough PR if you'd like)

https://github.com/usefathom/fathom/blob/da6ffde2eabb50433aa48000d1eee459b360930f/pkg/datastore/sqlstore/config.go#L10

**Comment by LKaemmerling** [comment]
I would prefer to leave the default config as "default" as possible. If you need to change the port you should switch to the URL which is already possible :)

**Comment by LKaemmerling** [comment]
I would prefer to leave the default config as "default" as possible. If you need to change the port you should switch to the URL which is already possible :)
