### ISSUE TITLE
Feature request: separated sites for different users

### ISSUE THREAD

**Issue by tenchooo** [usefathom/fathom#238]
Hi,

I think it could be useful if users can have their own separate sites, so one user can't see or delete sites added by someone else.

Would implement it myself but I have zero knowledge of Go....

**Comment by austinginder** [comment]
User management functionality was also mentioned in #175. That would solve a variety of situations like this. I would think at minimal new users should only have view only access.

**Comment by JackEllis** [comment]
Closed for #175
