### ISSUE TITLE
OpenID Connect and OAuth Support

### ISSUE THREAD

**Issue by Vad1mo** [usefathom/fathom#240]
It would be great if a user could Login with an existing OAuth or OIDC Provider and not just username password. 

Goth for example support many authentication options see: https://github.com/markbates/goth
This might be an alternative but less common provider in the enterprise field. https://github.com/dghubble/gologin

For Goth, you could basically use this example almost as is:
https://github.com/markbates/goth/blob/master/examples/main.go

**Comment by JackEllis** [comment]
@Vad1mo Thanks for the suggestion. We want to keep it simple, so username & password is what we're going to stick to... for now.

**Comment by Vad1mo** [comment]
Pitty, every org with more then 3 user want federated login. 

P.s. would you accept a PR if we made a contribution?

**Comment by JackEllis** [comment]
@vad1mo Unless we get a lot of people requesting this, it won’t go into the codebase. Additional authentication methods add extra maintenance down the road. Also, why do so many people in an org need access to analytics?
