### ISSUE TITLE
How to update if using one click install from Digital Ocean?

### ISSUE THREAD

**Issue by planetahuevo** [usefathom/fathom#242]
Hi, 
I found this instructions
https://github.com/usefathom/fathom/blob/master/docs/DigitalOcean%20One-Click%20Installation%20Instructions.md
But I am not able to find the "how to update" for installations that have been made like that.
What do you recommend?
Also, is there  any guide on how to migrate a install to another server? 

Thanks

**Comment by JackEllis** [comment]
Hi @planetahuevo,

There are no update instructions for the 1-click yet as there's nothing to update to. When we release the next update, we'll be adding instructions for upgrading the 1-click.

Thanks,

Jack

**Comment by planetahuevo** [comment]
I will wait then. 
I do not want to install something I do not know how I am going to update in the future.
