### ISSUE TITLE
Created user on DO Droplet, can't log in

### ISSUE THREAD

**Issue by cagrimmett** [usefathom/fathom#243]
I'm using the DO Droplet. 

I created a user with this syntax: `fathom user add --email="email@domain.com" --password="Pa55w0rd"`

I got the success message: `INFO[0000] Created user email@domain.com`

But when I try to log in with the email/password combo I just made, I get the error `Invalid username or password`

Is there another step I'm missing?

**Comment by JackEllis** [comment]
@cagrimmett Are you using the 1-click set-up? You may have to go to the directory that fathom is installed in (be in the same directory as the sqlite file) which, off the top of my head, is /home/fathom

**Comment by cagrimmett** [comment]
@JackEllis Thank you! I got confused because when I checked the directory I was in (root) there _is_ a `fathom.db` there. But when I went to `/home/fathom` and reran the command to create a user, it worked. Much appreciated.
