### ISSUE TITLE
No datas

### ISSUE THREAD

**Issue by valentin2105** [usefathom/fathom#244]
Hi,

I currently trying Fathom, seem a great tool,

I deployed the docker image in my Kubernetes cluster, exposed it with Nginx  +  TLS and passing RealIP and Forwarded_For header with $remote_addr value. 

Then I created a site, copied the JS to my website's footer, 
And then call my website from different locations (the tracker.js is loaded with http 200 without issue). 

But, 

I have not any data in my graph/dashboard.
Do I need to wait like one hour like GoogleAnalytics does ? 

Or maybe I'm wrong somewhere ?

PS: I don't have any referer meta on my web page. 

Thanks

**Comment by JackEllis** [comment]
There is a slight delay in the OS version, is the data displaying now?

**Comment by valentin2105** [comment]
Hi @JackEllis ,

No nothing showing after more than 8 hours :) 

The strange thing, 

The tracker.js is loaded in my webpage, GET http 200, and the brownser receive the JS. 
But **I don't see any logs** in Fathom (which run in Debug mode).

If I browse Fathom UI, of course I got a lot of logs. 
If I curl the tracker.js, I got logs. 

It's pretty like if my brownser request is ignored by Fathom, I don't know why. 

Thanks !

**Comment by JackEllis** [comment]
@valentin2105 Oh, it's probably ignored because you have DNT turned on.

**Comment by valentin2105** [comment]
Yeah, it was the problem,  DNT is included in chrome or an extension ? Thanks a lot.

**Comment by JackEllis** [comment]
Chrome setting :) np
