### ISSUE TITLE
Setting up authentication on a Docker instance

### ISSUE THREAD

**Issue by 416serg** [usefathom/fathom#246]
I deployed the docker version to Google Cloud's Kubernetes, however, I am having trouble understanding how to set up authentication on the server. Am I to SSH into the server and try to do it from there? When I tried to access the `fathom` command, I am unable to find a folder where it's defined. Thanks in advance!

**Comment by JackEllis** [comment]
https://docs.docker.com/engine/reference/commandline/exec/

Or we've built an automatic process if deploying on DO: https://github.com/usefathom/fathom/blob/master/docs/DigitalOcean%20One-Click%20Installation%20Instructions.md
