### ISSUE TITLE
Add goal page flow tracking

### ISSUE THREAD

**Issue by joepetrakovich** [usefathom/fathom#247]
All my email list signups redirect to a /thank-you/ page.  If I could add that url as a "goal" page and see the flow of a user from one page to that goal page, I would know how well my call-to-actions are performing for that prior URL.

**Comment by JackEllis** [comment]
Good idea @joepetrakovich! Any chance you're able to work on a PR for that? I have a series of other things that I'm going to work on when I get time, but a PR would help get this done.

**Comment by joepetrakovich** [comment]
Oh hmm I wouldn't know where to begin but I can give it a shot @JackEllis.
