### ISSUE TITLE
No pageviews showing for Heroku installation

### ISSUE THREAD

**Issue by nibl** [usefathom/fathom#248]
I have just installed Fathom on Heroku. There are no pageviews showing.
I have visited several pages on different devices/machines, but still zero stats. I have checked the Heroku logs and there are no errors or warnings. The server is running.

How do I locate the cause and fix it?

The site is https://thoughtson.org/

**Comment by JackEllis** [comment]
My guess is that they haven’t been aggregated yet. Check your stats today, still an issue?

**Comment by nibl** [comment]
Thanks you, stats have indeed now appeared.

What  is the typical aggregation period?

It would be good to mention this in the installation instructions after the final step where one pastes the tracking snippet. After a fresh installation I had no idea whether Fathom was working or not.

Thanks for making Fathom. We need software like this.
