### ISSUE TITLE
Thoughts on the UX

### ISSUE THREAD

**Issue by ziburski** [usefathom/fathom#25]
Hi! I’m excited about Fathom. I have been looking for and thinking about something like this for some time. It’s a challenging project from a business standpoint, so I believe keeping it really simple and narrow in scope is key.

I love that design seems to be a focus for Fathom, and @pjrvs is doing fantastic work. I wanted to share some ideas around the UX that have been on my mind for a while. This is from the perspective of editorial sites likes blogs, which are probably the primary use case for Fathom, right?

So Fathom right now is built around the core metrics of visitors, top content and referrals. I think that’s spot on. It’s the holy trinity of what most people will ever need on an ongoing basis.

Yet, these metrics only matter over time. It’s about how they change. Are there more visitors than before? Does my updated Facebook page drive more traffic than the old one? When exactly did my blog post go viral? Time gives these metrics context and meaning, which results in insights.

The most straightforward way to surface that change over time is a proper graph. Simple up / down arrows are fine as a first indicator, but lack context. And sparklines don’t really give you the option to dive in deeper or interact with the data. 

Here is a rough sketch of how the basic layout could work. You select a timeframe at the top, and the three sections below change accordingly. Maybe there could be a big visitor counter as part of the graph.

<img width="769" alt="fathom1" src="https://user-images.githubusercontent.com/1299080/39940519-dbec630e-5559-11e8-924b-502f77e099bc.png">

Now for the interesting part. I think the real power in these three data sets (visitors, content, referrals) is in their relation to each other. I want to know which of my blog posts was successful on Facebook, how a specific post did over a certain time frame, or where the visitors for that post came from. I want to explore these connections, and discover new insights on my own.

The simplicity of Fathom provides a great opportunity for an intuitive UI here. You could just click on any of the data points to filter all the other data for it. So if you click on a content page, you see the visitor graph and referrals for that page. If you click on a referral, you see the target pages and visitor graph for that referral. If you select a time frame on the graph, you see the content and referrals for that time frame.

<img width="771" alt="fathom2" src="https://user-images.githubusercontent.com/1299080/39940924-2fbed5d8-555b-11e8-9ed9-ba1f8a3f73e3.png">

It’s a super simple concept, but I think it’s powerful and intuitive for casual users.

Some quick notes on the metrics I left out:
- **Secondary metrics** like bounce rate, returning rate, page views, and time spent. These can have a lot of value depending on your needs, so it probably makes sense to include them. They aren’t core to the idea of this concept, but they should fit right in as sub-data of the visitor count.
- **Technology metrics** like display resolution, operating system or browser. These don’t really change over time, but a developer might want to check on them once a year or so. The same goes for location and language. If Fathom adds them eventually, I think they should be totally separate from the core, everyday analytics.
- **Business metrics** like funnels and event tracking. This seems like a deep rabbit hole to me. It’s where the money and the competition is. Fathom will have to figure out where it draws the line here to keep a unique positioning. Maybe there is an elegant way to get 80% of the benefits with 20% of the complexity, but it will still be difficult to avoid feature creep. Personally, I would err on the side of avoiding these for now.

Anyway, let me know what you think. I’d be happy to talk this through and develop it further if you think there could be something here. I know it’s still early days, so maybe I’m a bit overzealous here. But at least I got it out of my mind now. ;)

Thanks for working on this @dannyvankooten. Cheers!

**Comment by dannyvankooten** [comment]
Hey @ziburski,

This is awesome, thank you so much for dropping by and sharing your thoughts here. Paul and I have pretty much been thinking along the same lines so far, so I am glad it seems we are on the right track here.

**Re: metrics change is what matters**

Hear hear. I noticed that a lot of the data we track and visualise is based on certain assumptions and therefore it is not really the absolute numbers that matter, but how this number changes over time. 

**Technology metrics**

I recently came across [Gauges](https://get.gaug.es/), and they have the following page, which I really like. What are your thoughts on doing it like this (+ hidden from the main metrics).

![image](https://user-images.githubusercontent.com/885856/39955713-54cbc5d8-55d4-11e8-8d24-4c837ebbc784.png)

Also, please share how you are creating these sketches. They are gorgeous!

**Comment by ziburski** [comment]
Hey, good to hear we are on the same page! Do you think it could be useful as part of the open source process to also talk about design decisions in the open? I would love to follow along.

> I recently came across Gauges, and they have the following page, which I really like. What are your thoughts on doing it like this (+ hidden from the main metrics).

Gauges is great, but has sadly been abandoned for some time. If you do technology metrics, this seems like the way to go though. It’s the main use case for browser / platform metrics anyway. Maybe you can get more inspiration from caniuse.com, it’s like a personalised version after all. I wonder if it makes sense to show change over time here as well, and to what degree. 

> Also, please share how you are creating these sketches. They are gorgeous!

Thanks! I’m using [Linea Sketch](https://linea-app.com) on iPad with the Pencil. It works great for quick sketches you want to share.

**Comment by dannyvankooten** [comment]
Hey @ziburski,

I'm going to close this topic to keep the issue list clear & concise, but just wanted to let you know that we'd love to have you following along.

@pjrvs is setting up a public Fathom roadmap (most likely using Trello) so that everyone can follow along, vote for their favorite features and chime in on the discussion.

Cheers!
