### ISSUE TITLE
FATAL: kernel too old (OpenVZ)

### ISSUE THREAD

**Issue by Worldofmatthew** [usefathom/fathom#251]
It appears that fathom is incompatible with OpenVZ due to it using an older kernel version (2.6.32 based), which makes the application incompatible with a really large number of VPS's. 

Any tips around this or a patch for this would be good.

Thank You

Matthew Morgan

**Comment by lorenz** [comment]
2.6.32 is ancient, more than 10 years old. I would be seriously concerned about the security of any system based on a 10+ year old EOL kernel.

That aside: The specific error comes from glibc, which is used for the SQLite database which is written in C. If you're using a different database you should be able to build fathom with `env CGO_ENABLED=0 go build`, which will build with pure Go and thus avoid the glibc completely. The resulting binary should work on your VPS. But be aware that you're barely skirting by the official Go minimum kernel requirements by a few kernel versions, nobody tests on these kernels anymore, so even this is not a guarantee that it will work.

**Comment by JackEllis** [comment]
Yeah, EOL for 2.6.32 seems to be Nov of this year...
