### ISSUE TITLE
Track beforeunload event.

### ISSUE THREAD

**Issue by thebetterjort** [usefathom/fathom#254]
window.addEventListener('beforeunload', function(e) {
fathom('set', 'siteId', 'BEEYQ');
fathom('trackPageview');
});

We have PDFS stored offsite, and I would like to find out what are the most popular PDFS are.

**Comment by JackEllis** [comment]
That would fire every time a user changes page. I’m going to say no to this. If we have additional requests / a solid PR, we’ll review. As is, this code could not go into Fathom
