### ISSUE TITLE
No errors but also no metrics

### ISSUE THREAD

**Issue by Momomentum** [usefathom/fathom#255]
First of all thank you for your project efforts and community support.
I just installed fathom and set it up on my VPS. Everything appears to be running but the fathom dashboard doesn' t register any page hits.

My configuration is as follows:
Apache server for proxy:
```
<VirtualHost *:80>
    ServerName fathom.my-website.com
    ProxyPreserveHost On
    ProxyRequests Off
    <Location />
        ProxyPass http://localhost:9000/
        ProxyPassReverse http://localhost:9000/
    </Location>
</VirtualHost>
```

The Firefox Network tool shows the following:

![issue_fathoom](https://user-images.githubusercontent.com/12032318/55545467-8ae41a80-56cd-11e9-856d-894db02afbd7.png)

Request Header (GET tracker.js):
```
Host: fathom.my-website.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://my-website.com/
DNT: 1
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
```

Response Header:
```
HTTP/1.1 200 OK
Date: Thu, 04 Apr 2019 09:26:32 GMT
Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.1.27
Strict-Transport-Security: max-age=63072000; includeSubdomains
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
Accept-Ranges: bytes
Cache-Control: max-age=432000
Content-Encoding: gzip
Content-Type: application/javascript
Last-Modified: Wed, 03 Apr 2019 20:45:44 GMT
Tk: N
Vary: Accept-Encoding
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Content-Length: 1337
Keep-Alive: timeout=5, max=100
Connection: Keep-Alive
```

I would be very grateful for any hints of what is not working for me.

**Comment by JackEllis** [comment]
Stats take time to aggregate. Is the data there now?

**Comment by Momomentum** [comment]
Well thanks for clarifying and getting back so quickly. I got confused by by the current-visitor counter (left upper corner ), as I thought it would show if someone visited the site. Does it also take some time to register?

**Comment by Momomentum** [comment]
Well thanks for clarifying and getting back so quickly. Yes it works now! I got confused by by the current-visitor counter (left upper corner ), as I thought it would show if someone visited the site. Does it also take some time to register?
