### ISSUE TITLE
Subdomain vs IP address - net::ERR_CERT_COMMON_NAME_INVALID

### ISSUE THREAD

**Issue by helloitse** [usefathom/fathom#259]
I noticed that my fathom install is up and running, but there's no data coming in. 
When I check the console on the page I see these errors,

In Chrome: `Failed to load resource: net::ERR_CERT_COMMON_NAME_INVALID`
In Firefox: `Loading failed for the <script> with source “https://107.000.00.15/tracker.js”.`

Here's what I've put in the html:
`<script>
(function(f, a, t, h, o, m){
	a[h]=a[h]||function(){
		(a[h].q=a[h].q||[]).push(arguments)
	};
	o=f.createElement('script'),
	m=f.getElementsByTagName('script')[0];
	o.async=1; o.src=t; o.id='fathom-script';
	m.parentNode.insertBefore(o,m)
})(document, window, '//stats.enoma.co/tracker.js', 'fathom');
fathom('set', 'siteId', 'USPKV');
fathom('trackPageview');
</script>`

I have installed certbot and https works fine on stats.enoma.co. However, I don't have a ssl certificate for my actual ip address and I'm not sure why my ip is appearing in the console in the first place. Any thoughts?

**Comment by JackEllis** [comment]
Your stats link should use your stats.enoma.co domain, I wouldn’t recommend going over port 80 on the IP.

**Comment by helloitse** [comment]
Hey, so I'm not clear on what to do to fix it.

When I put the script in my HTML it says stats.enoma.co. Why/where would there be a switch that uses my ip address.

I'm not using port 80. I have a ghost installation on that port.

**Comment by helloitse** [comment]
> 
> 
> Your stats link should use your stats.enoma.co domain, I wouldn’t recommend going over port 80 on the IP.

Hey, so I'm not clear on what to do to fix it.

When I put the script in my HTML it says stats.enoma.co. Why/where would there be a switch that uses my ip address.

I'm not using port 80. I have a ghost installation on that port.

**Comment by JackEllis** [comment]
stats.enoma.co/tracker.js

That works fine for me
