### ISSUE TITLE
Track pageviews and referrers with doNotTrack enabled

### ISSUE THREAD

**Issue by dshook** [usefathom/fathom#262]
I'm certainly not the most versed on this topic but from the bit of research I did it looks like the "do not track" setting applies mainly to setting cookies and tracking longer sessions.

https://spreadprivacy.com/do-not-track/
https://www.eff.org/issues/do-not-track
https://en.wikipedia.org/wiki/Do_Not_Track

With that in mind, I'm proposing that when Fathom loads and detects the DNT setting it simply log the pageview and referrer and not set a cookie.  This would obviously help get the pageview numbers accuracy which are tracked via server logs regardless of DNT.

I'm assuming unique visitors is determined via the cookie so you could either count each new pageview as a new unique or count none of them as uniques.  I think it makes a bit more sense to count them as uniques but either way would suit me.

Thanks for the easy to set up software!

**Comment by m1guelpf** [comment]
Yes please

**Comment by pokrface** [comment]
I raised this issue via email with the developers back in January and pointed out that not logging PVs from DNT users creates a deviation between stats and reality, with that deviation growing larger and more impactful for sites with technical audiences more likely to have DNT enabled. They developers responded and explained they feel that "DNT" means "completely ignore this user and do not log any of their activity," full stop.

Between this and the decision to make 2.0 a paid-only product, I expect this issue to be closed with a WONTFIX.

**Comment by JackEllis** [comment]
@pokrface We have made no definitive stance on this yet. We believed that honouring DNT is right but are still discuss whether we need to honour DNT due to the fact that there’s no personal data being stored...

**Comment by dshook** [comment]
@JackEllis Any update on this?

Would a setting resolve your qualms leaving it up to the installer whether they want to track DNT page viewers or not?

**Comment by m1guelpf** [comment]
@dshook They've sent a survey asking for feedback to the paid version clients for v2, so I'd say they're working on this :)

**Comment by JackEllis** [comment]
@dshook Sorry for not giving an update. There is a lot of confusion & disagreement around the purpose of DNT, but you can now opt-in: https://usefathom.com/support/tracking-advanced
