### ISSUE TITLE
Allow CDN Serving of Tracking File

### ISSUE THREAD

**Issue by cjkoepke** [usefathom/fathom#264]
For some reason, when I load the tracking file via a CDN, the tracking does not work. I'm assuming because there's a check on the platform site to see if it's delivered via the same domain as the install (in this case, Digital Ocean).

But being able to serve through a CDN would be really great (even if that's more work for me to keep that file updated).

**Comment by JackEllis** [comment]
Accidentally closed, my bad, but you would likely need to modify the javascript file to get self-hosted to work with a CDN out the gate

**Comment by cjkoepke** [comment]
@JackEllis Why does serving from a CDN break the sending of data to Fathom? And by modifying the javascript file, I'm assuming you mean the tracker.js file, right?

**Comment by JackEllis** [comment]
Tracker.js, that’s right. Because when Fathom sends the /collect request, it uses the script src to get the URL to post to. I suppose you’d need to put a CDN across the whole app, not just the tracker.js file. CDN wasn’t really thought about with self-hosted.

**Comment by cjkoepke** [comment]
I see, so it's not really viable at this point without a pretty big update. Correct?

**Comment by JackEllis** [comment]
We have no plans for it on OS... BUT you can try modifying it yourself. Tweak it around etc. And you could do it

**Comment by cjkoepke** [comment]
Got it. Thanks!
