### ISSUE TITLE
Combine paths with and without trailing slash

### ISSUE THREAD

**Issue by weavermedia** [usefathom/fathom#269]
I'm seeing separate entries for `/about` and `/about/`.

I understand these are technically different resources but for analytics wouldn't  the count for these two paths be better combined?

**Comment by JackEllis** [comment]
Agreed!

**Comment by stef7** [comment]
Also agreed...

**Comment by JackEllis** [comment]
Would expect a 'right trim' on the /. Could cause issues for folks who NEED a trailing slash, but seems like that won't be many.

**Comment by olets** [comment]
- Looks like #348 changed this behavior, but I still see separate items in my site's "pages" dashboard pane. Is that expected?
