### ISSUE TITLE
Add privacy/security HTTP headers

### ISSUE THREAD

**Issue by StuartMorrisAU** [usefathom/fathom#273]
Please consider adding [privacy/security-related HTTP headers](https://securityheaders.com/?q=https%3A%2F%2Fusefathom.com%2F&followRedirects=on) to `*.*.usefathom.com`, such as:

- HSTS, and add to Chrome preload list
- Content-Security-Policy
- CORS
- X-Frame-Options
- X-XSS-Protection
- X-Content-Type-Options
- Referrer-Policy
- Feature-Policy

www.usefathom.com returns a certificate error. Should this redirect to https://usefathom.com instead?

**Comment by JackEllis** [comment]
@StuartMorrisAU Thank you sir.
