### ISSUE TITLE
Count ?ref= as a referrer instead of as a separate page

### ISSUE THREAD

**Issue by bcye** [usefathom/fathom#275]
When I add ?ref= to a URL, fathom counts that as a separate page instead of using it for the referral statd

**Comment by JackEllis** [comment]
@bcye We haven't announced it yet as we need to document it but you can now use ?ref=ProductHunt etc. No URL support, just keywords, and it'll appear as "Ref: Keyword" in the Referrers box. Thanks for raising this and sorry it took 1 year ;)

**Comment by bcye** [comment]
Awesome :) Will it still show up as a separate page?

**Comment by JackEllis** [comment]
@bcye Nope, it'll show up as a separate entry under Referrers. It's effectively a "Referrer Override" :) So if you went to bcye.com/about?ref=GitHub, you would see "Ref: GitHub" appear in the Referrals box.
