### ISSUE TITLE
Apache guide?

### ISSUE THREAD

**Issue by rhysperry111** [usefathom/fathom#276]
I am running an apache server and am having a really hard time forwarding analytics.mydomain.com to mydomain:8080 in order to get Fathom to work. When i succesfully get that to work I have a lot of errors where scripts are accessing the wrong locations e.t.c.

Can you please provide a tutorial for getting Fathom working with an apache server.

**Comment by JackEllis** [comment]
This looks like it will help: https://www.jessedyck.me/2019/02/self-hosting-fathom-analytics-behind-apache/
