### ISSUE TITLE
Visitor used in incorrect context in Web Analytics 

### ISSUE THREAD

**Issue by sredfern** [usefathom/fathom#277]
I feel that Fathom is using the term visitor in the incorrect context. In comparable web analytics solutions the term visitor is reserved for a persistent cookie measurement of a browser. Given the cookie expires and the measurement is unable to determine if that browser has come back to the website after the session has expired, the term Visit would be more appropriate.

A google search shows this terminology is common throughout the industry. 
https://www.google.com/search?q=pageview+visit+visitor&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiHysCFxJXjAhWXqp4KHclPBqgQ_AUIECgB&biw=1231&bih=1371

**Comment by JackEllis** [comment]
I agree. What do you think @pjrvs?

**Comment by JackEllis** [comment]
@sredfern We agree. Visit beats Visitor. We'll be changing things when we work on the iterations to this codebase :)
