### ISSUE TITLE
Can we record the user activity?

### ISSUE THREAD

**Issue by antoaravinth** [usefathom/fathom#28]
Hello, 

Thanks for this nice library. I was planning to create one from scratch (for learning purposes) and found this. Kudos..  I just wanted to check if there is a way for us to capture the activity of the user (and save it as a video)? IBM TeaLeaf does that and its very powerful too at times for debugging. So just wonders, if that can be achieved here as well.

**Comment by pjrvs** [comment]
thanks!

we have no plans to capture user activity as videos, as there are several solutions that do that well which exist already. it's not close to the core purpose of our app unfortunately.

cheers!
