### ISSUE TITLE
[Question] What is Timeout of Online Current Visitor

### ISSUE THREAD

**Issue by dx908** [usefathom/fathom#281]
I have a small query.

Let's say a user opens my site. He appears quickly in the reporting as online current visitors. 

Now if he doesn't do anything and keeps the tab opened for a long time in background. What is the timeout set in Fathom after it will remove the visitors from the "Current online" counter. Or whether they will stay online as long as the tab is opened in background? Even if it is couple of hours?

The reason I am asking is as Google Analytics Drops the user from online Real time if tab is left open longer than 5 minutes. Is the same timeout set in Fathom?

**Comment by JackEllis** [comment]
Testing my memory but I believe it's users from the last 5 minutes: https://github.com/usefathom/fathom/blob/45b28dba48aa0dc497108b381bfbfff952a7ed5a/pkg/datastore/sqlstore/site_stats.go#L67
