### ISSUE TITLE
Tutorial/Tips for server migration

### ISSUE THREAD

**Issue by shreyasminocha** [usefathom/fathom#282]
I want to migrate my self-hosted fathom instance to another server (and database). Any tips on how to do this?

**Comment by JackEllis** [comment]
We don't have a tutorial but it's super simple :)

1. Install Fathom on new server and set it up in the same way you did on your current server
2. Copy your SQLite file & replace the new one
3. Copy over the .env settings too (FATHOM_SECRET especially!)

And hey presto.
