### ISSUE TITLE
Feature Request: Integrate with AMP

### ISSUE THREAD

**Issue by regpaq** [usefathom/fathom#283]
Open to integrating with AMP? https://amp.dev/documentation/guides-and-tutorials/contribute/integrate-your-analytics-tools/?format=websites

**Comment by m1guelpf** [comment]
@jackellis Any chance of considering this for v2?

**Comment by JackEllis** [comment]
@m1guelpf Potentially. We've closed up our V2 scope now so we're not bringing in anything new. We could consider for 2.1 We've already punted an exciting new feature (secret at present) to Version 2.1

**Comment by EnKrypt** [comment]
Whether or not this project gets AMP integration support is of course up to the author and maintainers, but I think I should put forth the argument that AMP is doing a lot more harm than good, and the general consensus within the developer community, especially those geared towards privacy and user control, is that we *should not* adopt this standard.

https://www.theregister.co.uk/2017/05/19/open_source_insider_google_amp_bad_bad_bad/

**Comment by JackEllis** [comment]
@EnKrypt Thanks for the input, Arvind. I've actually heard a lot of bad things about AMP in the past but I've not had a chance to dive in. I'm sure @pjrvs has his finger on the pulse with this. If it's an anti-privacy / anti-competitive behaviour then it won't be included.

**Comment by pjrvs** [comment]
AMP stores content from your site on Google's servers, so I'm not interested in integrating with AMP since Fathom has a fairly hard stance against "the goog". :)

**Comment by JackEllis** [comment]
Yikes... Closing this up.
