### ISSUE TITLE
multiple domains connected to one site

### ISSUE THREAD

**Issue by shecodes30** [usefathom/fathom#284]
I have written multiple blogs in various different niches. I've been recommended to have them all under one site rather than multiple blog sites to keep costs down and make it easier to promote via social media as multiple blog sites would mean I'd need multiple social media accounts for each blog. 

Could I have a different domain for each blog but direct them all to one site? I am using WordPress to create each blog. Would it be at all possible to host them all under one website or would these cause complications? I'm guessing that having different domains for each blog could help generate traffic with an SEO friendly domain for each different niche. Am I stupidly incorrect? or could this be a good idea which is possible? 

If it is possible how would I do this, please?

**Comment by JackEllis** [comment]
Best thing to do is 1 site per domain. I advise against multiple domains under a single site, but it is possible.
