### ISSUE TITLE
[Request] WordPress plugin to ignore hits from logged in admins

### ISSUE THREAD

**Issue by dsingleton86** [usefathom/fathom#286]
Would it be possible for the WordPress plugin to detect logged in admin accounts and not track those hits from displaying in Fathom?
Maybe even have options to pick which user levels are/aren't tracked?
Thanks

**Comment by JackEllis** [comment]
I like this idea a lot. We'll get round to this asap.

**Comment by BrookeDot** [comment]
One simple way to do this is to use `wp_footer` and `is_logged_in` this works if you don't have logged in visitors who are not admins. If you want to check the role you can modify the code with something like the [example here](https://wordpress.stackexchange.com/questions/5047/how-to-check-if-a-user-is-in-a-specific-role).

```
function add_fathom() {
   if( ! is_logged_in ) {
    echo ( 'Tracking code here' ); // this could also be used with wp_enqueue_script
 }
}
add_action( 'wp_footer', 'add_fathom' );
```

This could of course be built out into a plugin though.

**Comment by JackEllis** [comment]
This is done & live btw
