### ISSUE TITLE
Ignore requests from localhost

### ISSUE THREAD

**Issue by EnKrypt** [usefathom/fathom#287]
I'm hosting fathom myself on a docker container and I see in the dashboard that it's captured some requests from localhost. (Probably my own activity during development)

Is there a way to blacklist localhost or any other specific host? I did go over some of the other issues and commits that seem to address this, but they don't seem to have applied in my case, or no longer work.

**Comment by EnKrypt** [comment]
Bumping cause it's been more than a week. No rush, just want to confirm or deny that this is possible. @JackEllis

**Comment by JackEllis** [comment]
Hi there - not at the moment but you could wrap a check around the trackPageview function to stop it. If you struggle with the code, let me know your URL path (if it’s not localhost) and I’ll send you some code to stop tracking on localhost

**Comment by EnKrypt** [comment]
@JackEllis I ended up doing just that.

When you have the time, can you review the PR I submitted?
