### ISSUE TITLE
Support NoSQL datastores

### ISSUE THREAD

**Issue by zengabor** [usefathom/fathom#29]
I would like to use Fathom in an environment where disk storage isn't permanent, and using an SQL database would cost too much while a great NoSQL datastore is already available. I would like to implement the relevant parts in Fathom so that others in a similar situation can use it.

Do you think this could be doable in some way? I checked the code just today, only briefly, and the queries look rather straightforward so a transformation doesn't look impossible, but I am not sure.

**Comment by zengabor** [comment]
Sounds great. This would be [Google Cloud Datastore(https://cloud.google.com/datastore/). I’ve worked with it for several years so I could implement it once the abstraction is in place.

In the long term [Google BigTable](https://cloud.google.com/bigtable/) looks also interesting.

**Comment by JackEllis** [comment]
@zengabor We've not had any additional requests for this. Can you correct me if I'm wrong here, but using an SQL database on Google Cloud costs $10 per month in europe-west6... Based on that, the dev time, and the lack of additional requests for this, I'm afraid we can't bring this in ahead of other priorities we have. If I'm incorrect about the cost of Cloud SQL on Google, please let me know.

**Comment by zengabor** [comment]
That is absolutely fine. (Not sure about the pricing, didn't check it since then. Note that some of us have multiple environments, so that multiplies the price.)
