### ISSUE TITLE
Conversion Rate

### ISSUE THREAD

**Issue by knorthfield** [usefathom/fathom#298]
Would be great to link a goal to a page so a conversion rate could be calculated i.e. goals/pageviews.

Would also be good to have funnels. I like the way Fullstory does funnels, you just select a list of pages (or goals I suppose).

**Comment by m1guelpf** [comment]
@knorthfield I get this is feedback for the new Fathom hosted version? If so, I don't think they check this repo a lot, you'd be better of [emailing them](mailto:support@usefathom.com) 😄
