### ISSUE TITLE
Cookie Use

### ISSUE THREAD

**Issue by realseanwatson** [usefathom/fathom#300]
Hello, This is not an issue, I have been looking around for a Comment Section to no avail... 

I just tested this (Lite Version) and I like the idea of being focused on Privacy, it has a nice UI and I can see the quality work that was put in place to have this done. 

I note you said that this is not PECR compliant (Which would cause user privacy concerns), as this uses an unknown cookie. Are you able to say when this will be addressed as I would really like to start using this in production? I am running an E-Commerce Store and I want to make sure that privacy is key and I stopped using G Analytics when I saw this system, that is how serious I am about "Protecting User Data."

As I said I am not sure if this is the right place to post this, I am a bit new to GitHub and its usage.
Thanks!

**Comment by fjeddy** [comment]
From what I understand, then cookies are only a problem with PECR and GDPR if it's coming from third parties, like Google Analytics, Facebook, Disqus and so on.

If you're hosting the analytics software yourself, then no cookie message is necessary, as no third party is involved.

GDPR and PECR is in place to enlighten and inform the users of data that's being shared, when everything is controlled, hosted and ran by you, then no data is shared, and hence, you are GDPR compliant.

**Comment by m1guelpf** [comment]
Hey!

Right now this repository is not mantained (though as far as I'm aware of it's going to be in the future), so I don't think this is going to get supported in the near future. If cookieless analytics are a hard requirement, you could check out [Fathom v2](https://usefathom.com), which doesn't use any kind of cookies. Still, if you have the knowledge to PR this, it might be considered in the future.

**Comment by JackEllis** [comment]
Full disclosure: We have plans for an update to the repository but it doesn't include PECR compliance.
