### ISSUE TITLE
Change tracker.js filename?

### ISSUE THREAD

**Issue by MACscr** [usefathom/fathom#303]
Is there a way to easily change the tracker.js filename to something else and have panel give the updated path for snippets? tracker.js is going to be be blocked by default by most adblockers simply because of its name.

**Comment by m1guelpf** [comment]
The easiest way would be doing this from the server, that is, Nginx or any other proxy you're using (if you are using the server binary directly just skip this). With Nginx, for example, you can proxy one path to another, [here's an article that explains different ways of achieving this](https://www.nginx.com/blog/creating-nginx-rewrite-rules/). This way, you could proxy `fathom.js` (or whatever other name you choose) to `tracker.js`.

If you want to go the hard way, you could edit the souce and rebuild the binary. For this, you'd have to rename `assets/src/js/tracker.js` and update the name [here](https://github.com/usefathom/fathom/blob/master/assets/src/js/tracker.js#L105), then update [this line of the gulpfile](https://github.com/usefathom/fathom/blob/master/gulpfile.js#L36) and finally lines 38 and 50 of [the routes](https://github.com/usefathom/fathom/blob/master/pkg/api/routes.go). After that is done, you can follow [these instructions](https://github.com/usefathom/fathom#development) to build a new binary, then use it as usual.
