### ISSUE TITLE
Fast page refreshing, triggers new unique current visitors

### ISSUE THREAD

**Issue by stenvdb** [usefathom/fathom#304]
When I refresh a site quite fast, the current visitors number keeps increases. So each (fast) refresh is triggered as a new unique visitor. I'm guessing this has something to do with the event listener which isn't being triggered: https://github.com/usefathom/fathom/blob/8f7c6d2e45ebb28651208e2a7320e29948ecdb2c/assets/src/js/tracker.js#L179

**Comment by JackEllis** [comment]
@stenvdb I expect so. The image is loading but the event doesn't have time to fire & set the cookie by the looks of it.
