### ISSUE TITLE
Unable to call `trackPageview` with custom path

### ISSUE THREAD

**Issue by vpicone** [usefathom/fathom#305]
Would like to add fathom tracking to our storybook. Storybook has `STORY_CHANGED` event where I'd like to call `trackPageview` with `{path: /story-path}`. However, it doesn't seem to be working, all I can register is the root path.

Repro:
1. create a new site, 
2. Create a new `dir/index.html` document with a button to fire the trackPageview event. Be sure to replace your site ID in the example below.
3. run `npx serve dir`
4. click button

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>
  <body>
    <button onClick="myClick()">
      click
    </button>
    <script>
      (function(f, a, t, h, o, m) {
        a[h] =
          a[h] ||
          function() {
            (a[h].q = a[h].q || []).push(arguments);
          };
        (o = f.createElement('script')),
          (m = f.getElementsByTagName('script')[0]);
        o.async = 1;
        o.src = t;
        o.id = 'fathom-script';
        m.parentNode.insertBefore(o, m);
      })(document, window, '//cdn.usefathom.com/tracker.js', 'fathom');
      fathom('set', 'siteId', 'SITE_ID_HERE');
      fathom('trackPageview');
      function myClick() {
        window.fathom('trackPageview', { path: '/wompy' });
      }
    </script>
  </body>
</html>
```

**Comment by JackEllis** [comment]
@vpicone We'll get a change made. For now, you can use

`window.fathom('track', { path: '/wompy' }, 'pageview');`

And that should work great. Sorry for the delay in getting back to you here, if you email support@usefathom.com we typically reply quickly :)
