### ISSUE TITLE
fathom extraction fails (Heroku)

### ISSUE THREAD

**Issue by skuzzymiglet** [usefathom/fathom#308]
```
$ curl -s https://api.github.com/repos/usefathom/fathom/releases/latest \
  | grep browser_download_url \
  | grep linux_amd64.tar.gz \
  | cut -d '"' -f 4 \
  | wget -qi - -O- \
  | tar --directory bin -xz - fathom
tar: -: Not found in archive
tar: Exiting with failure status due to previous errors
```

This is from the docs at https://github.com/usefathom/fathom/blob/master/docs/misc/Heroku.md#create-the-app

**Comment by skuzzymiglet** [comment]
This needs attention as it's preventing people from using this on heroku

**Comment by leonardofaria** [comment]
Hi @skuzzymiglet 
I followed the same instructions of the doc and it worked just fine. Maybe a temporary error?
