### ISSUE TITLE
Update Digital Ocean Marketplace droplet

### ISSUE THREAD

**Issue by kbreit** [usefathom/fathom#311]
The Digital Ocean Marketplace droplet is still on Fathom 1.2.1 instead of 2.0. I'd also like to see instructions on how to upgrade the Marketplace droplet.

**Comment by JackEllis** [comment]
@kbreit Fathom 2.0 is a paid product (see https://usefathom.com). We'll be releasing 1.3 of Fathom Lite some time this year
