### ISSUE TITLE
Errors will happen when upgrading the library

### ISSUE THREAD

**Issue by KateGo520** [usefathom/fathom#315]
(The purpose of this report is to alert `usefathom/fathom` to the possible problems when `usefathom/fathom` try to upgrade the following dependencies)

### github.com/urfave/cli  
-Latest Version: v2.2.0 (Latest commit d648edd on 6 Mar)
-Where did you use it: 
https://github.com/usefathom/fathom/search?q=urfave%2Fcli&unscoped_q=urfave%2Fcli
-Detail: 
>[github.com/urfave/cli/go.mod](https://github.com/urfave/cli/blob/v2.2.0/go.mod#L7)
```
module github.com/urfave/cli/v2
go 1.11
require (
	github.com/BurntSushi/toml v0.3.1
	github.com/cpuguy83/go-md2man/v2 v2.0.0-20190314233015-f79a8a8ca69d
	gopkg.in/yaml.v2 v2.2.2
) 
```

>[github.com/urfave/cli/docs.go](https://github.com/urfave/cli/blob/v2.2.0/docs.go#L11)
```
package cli
import (
	"github.com/cpuguy83/go-md2man/v2/md2man"
	…
) 
```
This problem was introduced since **_urfave/cli v1.22.1_** . If you try to upgrade  **urfave/cli** to version ** v1.22.1** and **above**, you will get an error--- **_no package exists at "github.com/cpuguy83/go-md2man/v2/md2man"_**

## I investigated the libraries  (**urfave/cli >= v1.22.1**)  release information and found the root cause of this issue is that---- 
1.	These dependencies all added [Go modules](https://github.com/golang/go/wiki/Modules) in the recent versions.

2.	They all comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. Quoting the specification:
> A package that has migrated to Go Modules _must_ include the major version in the import path to reference any v2+ modules. For example,  Repo github.com/my/module migrated to Modules on version v3.x.y.  Then this repo should declare its module path with MAJOR version suffix "/v3"  (e.g., module `github.com/my/module/v3`), and its downstream project should use `"github.com/my/module/v3/mypkg"` to import this repo’s package.

3.	This "github.com/my/module/v3/mypkg" is not the `physical path`. So earlier versions of Go (including those that don't have minimal module awareness) plus all tooling (like dep, glide, govendor, etc) don't have `minimal module awareness` as of now and therefore don't handle import paths correctly See [golang/dep#1962](https://github.com/golang/dep/issues/1962), [golang/dep#2139](https://github.com/golang/dep/issues/2139).
> Note: creating a new branch is not required. If instead you have been previously releasing on master and would prefer to tag v3.0.0 on master, that is a viable option. (However, be aware that introducing an incompatible API change in master can cause issues for non-modules users who issue a go get -u given the go tool is not aware of semver prior to Go 1.11 or when module mode is not enabled in Go 1.11+).
> Pre-existing dependency management solutions such as dep currently can have problems consuming a v2+ module created in this way. See for example dep#1962.
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

### 1. Migrate to Go Modules.
Go Modules is the general trend of ecosystem, if you want a better upgrade package experience, migrating to Go Modules is a good choice.

Migrate to modules will be accompanied by the introduction of virtual paths(It was discussed above).
> This "github.com/my/module/v3/mypkg" is not the `physical path`. So Go versions older than 1.9.7 and 1.10.3 plus all third-party dependency management tools (like dep, glide, govendor, etc) don't have `minimal module awareness` as of now and therefore don't handle import paths correctly.

Then the downstream projects might be negatively affected in their building if they are module-unaware (Go versions older than 1.9.7 and 1.10.3; Or use third-party dependency management tools, such as: Dep, glide, govendor…).

**[*]** You can see who will be affected here: [1 module-unaware users, i.e., ExploreDigital/stealth]
https://github.com/search?q=usefathom%2Ffathom+filename%3Avendor.conf+filename%3Avendor.json+filename%3Aglide.toml+filename%3AGodep.toml+filename%3AGodep.json

### 2. Maintaining v2+ libraries that use Go Modules in Vendor directories. 
If `usefathom/fathom` want to keep using the dependency manage tools (like dep, glide, govendor, etc), and still want to upgrade the dependencies, can choose this fix strategy.
Manually download the dependencies into the vendor directory and do compatibility dispose(materialize the virtual path or delete the virtual part of the path). Avoid fetching the dependencies by virtual import paths. This may add some maintenance overhead compared to using modules.

As the import paths have different meanings between the projects adopting module repos and the non-module repos, materialize the virtual path is a better way to solve the issue, while ensuring compatibility with downstream module users. A textbook example provided by repo `github.com/moby/moby` is here:
https://github.com/moby/moby/blob/master/VENDORING.md
https://github.com/moby/moby/blob/master/vendor.conf
In the vendor directory, `github.com/moby/moby` adds the **/vN** subdirectory in the corresponding dependencies.
**This will help more downstream module users to work well with your package.**

### 3. Request upstream to do compatibility processing.
The `urfave/cli` have 1694 module-unaware users in github, such as: alena1108/cluster-controller, nathan-jenan-rancher/example-kontainer-engine-driver, containerd/containerd…
https://github.com/search?q=urfave%2Fcli+filename%3Avendor.conf+filename%3Avendor.json+filename%3Aglide.toml+filename%3AGodep.toml+filename%3AGodep.json

## Summary
You can make a choice when you meet this DM issues by balancing your own development schedules/mode against the affects on the downstream projects.

For this issue, Solution 1 can maximize your benefits and with minimal impacts to your downstream projects the ecosystem. 

## References
* https://github.com/golang/go/wiki/Modules#semantic-import-versioning
* https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
* https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

Do you plan to upgrade the libraries in near future?
Hope this issue report can help you ^_^
Thank you very much for your attention.

Best regards,
Kate

**Comment by KateGo520** [comment]
@JackEllis   @amureki

**Comment by KateGo520** [comment]
@JackEllis  @A5hleyRich Could you help me review this issue? Thx :p

**Comment by KateGo520** [comment]
By the way, have you ever encountered such errors when upgading the libraries?

**Comment by JokerQyou** [comment]
I've actually dealt with this problem in my own fork, and went with the first way: migrating to go mod. I've also stopped vendoring dependencies. The relevant commits are [this](https://github.com/JokerQyou/fathom/commit/b887a5a5ff9405aa35e98d6d3458762d66a52043#diff-37aff102a57d3d7b797f152915a6dc16R25) and [this](https://github.com/JokerQyou/fathom/commit/3a642ea595957550d564a4018c95de804d239c39#diff-37aff102a57d3d7b797f152915a6dc16R28).

**Comment by KateGo520** [comment]
@JokerQyou  Wish you every success in migrating to Go Modules！
