### ISSUE TITLE
Self Hosted instance does not have Gear icon in UI

### ISSUE THREAD

**Issue by mmartinsky** [usefathom/fathom#325]
Steps:

```
$ docker run -d -p 8080:8080 usefathom/fathom:latest
Unable to find image 'usefathom/fathom:latest' locally
latest: Pulling from usefathom/fathom
c9b1b535fdd9: Pull complete 
1555fcd18f9e: Pull complete 
4850b46a4812: Pull complete 
5dd2917be6a2: Pull complete 
Digest: sha256:c8270f9e2bd93788509dec1de78f29a0084a7b492530351b269b7930aa365859
Status: Downloaded newer image for usefathom/fathom:latest
d40aae7b0ad6b7fcbdb6e0b51e27ca63fbfb6b2d6aa1f7ef6d5a95cf41472d13
```

1. Go to localhost:8080
2. Enter Site Name in Modal
3. Click elsewhere to close modal

Reading https://github.com/usefathom/fathom/blob/master/docs/FAQ.md#how-to-start-tracking-pageviews, there should be a gear icon - I don't see one here, but could easily be user error.

![image](https://user-images.githubusercontent.com/9168958/92941837-dea87680-f41e-11ea-96cf-dd64d2fcb361.png)

**Comment by JackEllis** [comment]
You need to login to see it, I believe.
