### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by Ashtonian** [usefathom/fathom#336]
Sorry to open an issue _but_  - what is the status of this project and will it be maintained going forward? I can see the fathom product is still very much alive. This project hasn't had any merged prs or commits in 2 years and last official release was in 2018. There are several open PRs and [some](https://github.com/usefathom/fathom/pull/208) of which are really cool.  Any updates? 

Thank you for providing it in the first place, its a cool project.

**Comment by kallisti5** [comment]
Project looks dead to be honest..  It's a bit weird Fathom is still selling the product, but no longer updating it :-\

We are using it, and I came to ask for settings in environment variables so we could easily migrate it to k8s.

**Comment by kallisti5** [comment]
https://github.com/samuelmeuli/fathom/issues/1

**Comment by S1SYPHOS** [comment]
I'd love to hear from @JackEllis - I guess they didn't want to drag the `free` variant around, so they moved the actual code to a private repository .. very disappointing, actually :disappointed:

**Comment by S1SYPHOS** [comment]
Hey there @JackEllis,
first of all: thanks for letting us know - like many people in the community, I'm actively using (and to some degree endorsing) `fathom` as privacy-first analytics tool.

I didn't know (and I guess others too) that the software actually being used isn't written in Golang - as opposed to the self-hosted project - and therefore couldn't have guessed that you were _in need of a developer in order to maintain it_. Needless to say that many rely on open source (privacy-focused) because of its transparency - but I totally understand that maintaining a small (but luckily growing, congratulations!) business takes its toll.

I cannot provide any Golang knowledge as of now, but would love to see the community partake in this - opening up as a company might be crucial here.

Thanks for your honesty, your time and consideration 

cheers
S1SYPHOS

**Comment by S1SYPHOS** [comment]
**// Update:** This may (totally) be a longshot, but I know that @fnetx and the guys from https://codeberg.org are skilled Go developers, contributing to @go-gitea for their hosting service. I get the feeling that `fathom` would align really well with their philosophy IMHO, so maybe there's an interest to contribute in any way - if not, sorry for tagging!

**Comment by LKaemmerling** [comment]
> Hey folks,
> 
> Thanks for the tag @S1SYPHOS, I had missed this.
> 
> Few things to clear up:
> 
> 1. This codebase is for self-hosting and is written in Go. We don't write Go, so it's not something we can casually update. We've had plans to bring in Go developers but we're a tiny team managing a business.
> 2. None of the code here is used in a private repository. The private repository that powers usefathom.com was built by myself and Paul, in Laravel, when we "restarted" the company in Canada, when the original developer left the project.
> 
> In terms of where I want to take this next:
> 
> 1. We _need_ a Go developer to come in and fix some of the bugs. It's not cool that we have open PRs that could be merged and haven't been. And I genuinely apologize for that.
> 2. Our focus is on our paid product, and this will exist and be maintained.
> 
> @LKaemmerling Please can we talk about this. I know you're busy right now but you'd be an ideal partner to handle some of these PRs and perhaps fix some bugs. Let me know if you're open to this. I'm completely slammed right now for time as it is, so I can't play around with Go, but if you think you can help handle some PRs & bugs, you'd make folks here very happy.

Of course I will have a look later today :) Maybe I can already do a bit!

**Comment by kallisti5** [comment]
@JackEllis so, in true open-source fashion, you technically don't need to hire a go-lang developer.

I think the community is sizable enough if you could just find a little time / man-power  to dedicate to reviewing pull requests, you could navigate the overall direction of the go-lang fathom port.

However, If the go-lang fathom no longer interests you... you could technically find someone to fork and maintain the project under a different name (to avoid brand confusion).

**Comment by JackEllis** [comment]
@kallisti5 This codebase is called Fathom Lite, and we document it here (https://usefathom.com/lite). That's our way to distinguish on it. We do believe people should be able to host a lightweight solution with ease.

Sounds like Lukas is up for it, so we can move things forward! Not too interested in working with new people right now, so this is a huge win.

**Comment by JackEllis** [comment]
@Ashtonian @kallisti5 @S1SYPHOS Closing this now. I have spoken to Lukas, who works with us on our paid product, and he's going to work on maintaining (getting bugs squashed & merging PRs). We have no plans to release any new features right now, this is solely a maintenance venture, but this is the first step. I've felt bad about the fact we've had a couple of bugs, but no releases to fix them, for a while now. Let's see where this goes.

**Comment by S1SYPHOS** [comment]
I think for now this is a start - PRs being reviewed and merged, including feature commits from the community, right?

Thanks for that.

**Comment by JackEllis** [comment]
@S1SYPHOS Too early to say. The objective of Fathom Lite is to be a super lightweight analytics product. And with every feature added, maintenance increases. Let's start with what we've got now and then see what happens.

**Comment by S1SYPHOS** [comment]
@JackEllis I was thinking about no-cookie as a feature, which would not necessarily increase maintenance but could be seen as feature 😀

**Comment by JackEllis** [comment]
@S1SYPHOS  Oh I see! Yeah I need to speak with Paul, as we are slammed right now, but something like that could be something we accept.

**Comment by istiak101** [comment]
We have internally forked this. And added few features. Not sure yet if we should open the source.

1) Multiple user with site ownership (Each user can have their own sites)
2) Switch to urfave/cli/v2
3) Updated go version to 1.23
4) Advanced bot detection
5) User agent and visitor IP storage in pageviews
6) Rebranding

TODO
1) Remove packr and migrate to gin. This would result almost a complete rewrite
2) Rewrite frontend completely
