### ISSUE TITLE
Draft new release

### ISSUE THREAD

**Issue by kallisti5** [usefathom/fathom#349]
v1.2.1 was released Nov 30, 2018.
Several new fixes have been committed to "fathom lite", so a new release might be warranted.

Release notes:
  * Postgres 14 support
  * npm security updates
  * unit test fixes
  * enhancements to search engines

Here are the steps i've personally used for Haiku's version of master...

```
docker build -t docker.io/haiku/fathom:version .
```

For fathom, this is likely along the lines of what you want to do: (change the version to "whatever"):

```
docker build -t docker.io/usefathom/fathom:v1.3.0
docker push docker.io/usefathom/fathom:v1.3.0
```

I wouldn't build to "latest" since thats pretty bad form now-a-days in a kubernetes world.

I'm just mentioning this here since i'm not sure how much knowledge was retained about fathom lite.

**Comment by LKaemmerling** [comment]
Hey @kallisti5,

we will release something shortly :) Thanks! I just want to get rid of all open issues/MRs so that we are again in a clean state.

**Comment by kallisti5** [comment]
@LKaemmerling thanks!  Let me know if you need any help.    Haiku uses fathom lite and it has served us well for multiple years.  Glad it's seeing a little maintenance.

**Comment by geerlingguy** [comment]
Ooh, count me in too. Btw, I don't have the revenue on my sites to justify paying for https://usefathom.com, but would gladly chip in something on GitHub Sponsors since Fathom has been so helpful for all my tiny sites. Something to consider!

**Comment by LKaemmerling** [comment]
So i'm now basically ready. I just have one MRs that needs to be tested/merged on a bigger setup than mine :) (I will test it a bit more tomorrow to) (https://github.com/usefathom/fathom/pull/353) and then we are good to go IMHO. All dependencies are up 2 date as of https://github.com/usefathom/fathom/pull/355 and all issues/MRs are closed :)

**Comment by eddsalkield** [comment]
Any progress on this? :)

**Comment by LKaemmerling** [comment]
FYI v1.3.0 was released 3 days ago: https://github.com/usefathom/fathom/releases/tag/v1.3.0
