### ISSUE TITLE
Is the self-hosted version as fully featured as the cloud version?

### ISSUE THREAD

**Issue by nnthuanegany** [usefathom/fathom#364]
Hi, I have some questions, I hope you can help me answer them, I sincerely thank you!
- Is the self-hosted version as fully featured as the cloud version?
- Is there a place that lists the features of the self-hosted version?

**Comment by LKaemmerling** [comment]
Hey @nnthuanegany,

there is a feature comparison visible on the Readme: https://github.com/usefathom/fathom#fathom-lite-vs-fathom-analytics Fathom lite and Fathom cloud are does not have the same features.
