### ISSUE TITLE
npm install and folder /storage/sessions

### ISSUE THREAD

**Issue by ghost** [usefathom/fathom#4]
During the installation process I had to ``npm install`` and create the folders ``/stroage/sessions``, maybe that should be added to the installation process / readme.

**Comment by metalmatze** [comment]
Just ran into the same problem. So yes, please add this.

**Comment by dannyvankooten** [comment]
Way too late as I got tracked (for which I am sorry) but I'm in a much better place to take care of this project now, so here we go.

Thanks for the suggestion! No longer storing sessions on the filesystem + fixed by @jro7 in e8f389d45ad3182290b76a663e6d5434610bb4a2.
