### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by ziburski** [usefathom/fathom#42]
Not sure about the best way to suggest edits to the readme and Wiki, I hope this is fine. Just some small things I stumbled upon when setting up Fathom for the first time:

- The readme says `replace yourfathom.com with the URL to your Fathom instance (twice).` There is only one instance.
- The set up guide in the Wiki doesn’t mention that you have to register a new user.
- It also refers to localhost, which is a little misleading if you are actually setting up a production server.

Other than that, set up was a breeze. I went from creating the server to running Fathom in less than 5 minutes. 👍

**Comment by dannyvankooten** [comment]
Hey @ziburski,

These are great suggestions. Thanks a lot! I'll get that improved upon. :)

**Comment by dannyvankooten** [comment]
Updated the [installation guide](https://github.com/usefathom/fathom/wiki/Installing-&-running-Fathom):

- Stop referring to `localhost`
- Mention user registration step
