### ISSUE TITLE
Relative time frames

### ISSUE THREAD

**Issue by ziburski** [usefathom/fathom#43]
Right now, the premade time frames are:

- Today
- This Week
- This Month
- This Year

These aren’t much help if you are early into a week / month / year. Wouldn’t it make more sense to have:

- Today
- Last 7 days
- Last 30 days
- Last year

Alternatively (or additionally), it could also be interesting to overlay the previous instance of that time frame. So when you select this month, you can toggle a curve for last month as well. That adds some complexity though.

Either way, it would be nice to have easy access to relative time frames.

**Comment by dannyvankooten** [comment]
Hey Lennart,

We've been contemplating this when we initially started the work on a rough version 1 and were torn between the two: "this" vs "last" periods. 

With the datepicker now added and basically showing rows or blocks of "this" (eg this month is the initial datepicker view) I think that tilted the preset periods to be slightly better off using relative time frames?

Also not sure if this is at all clear, but you can click the dates in the top right corner to open up a datepicker and set your own custom date ranges. Did you notice? If not, we should do something about that too. :)

**Comment by ziburski** [comment]
> With the datepicker now added and basically showing rows or blocks of "this" (eg this month is the initial datepicker view) I think that tilted the preset periods to be slightly better off using relative time frames?

To me, it’s just that “last x days” is vastly more useful and what I want 90% of the time. I don’t usually need to map the data to a static view of this specific week / month, I just want to figure out past trends. Using the date picker for switching is pretty tiresome, especially if I want to adjust it every time for the last x days.

Maybe others have different use cases though.

> Also not sure if this is at all clear, but you can click the dates in the top right corner to open up a datepicker and set your own custom date ranges. Did you notice? If not, we should do something about that too. :)

The UI is very clean, so it’s easy to figure out. But yeah, making them a little more clickable might be good.

Have a nice weekend! :)

**Comment by albinekb** [comment]
I like how Firebase Analytics did this: ![kapture 2018-06-11 at 18 48 03](https://user-images.githubusercontent.com/5027156/41245308-fd079ed0-6da7-11e8-91a9-c87d12abe0fe.gif)

**Comment by dannyvankooten** [comment]
That does indeed look nice @albinekb, thanks for sharing! The presets they use look to make sense for me as well.
