### ISSUE TITLE
(Issue): packr: No such file or directory

### ISSUE THREAD

**Issue by antoaravinth** [usefathom/fathom#44]
Hello, 

Thanks for this nice project. However, looks like I couldn't able to run `make build` successfully. 

Here is the issue I get:

```
[20:19:09] Using gulpfile ~/programs/go/fathom/gulpfile.js
[20:19:09] Starting 'browserify'...
[20:19:09] Starting 'sass'...
[20:19:09] Starting 'html'...
[20:19:09] Starting 'img'...
[20:19:09] Starting 'minify'...
[20:19:15] Finished 'html' after 5.45 s
[20:19:15] Finished 'minify' after 5.45 s
[20:19:15] Finished 'img' after 5.46 s
[20:19:15] Finished 'sass' after 5.8 s
[20:19:17] Finished 'browserify' after 7.65 s
[20:19:17] Starting 'default'...
[20:19:17] Finished 'default' after 56 μs
packr build -v -ldflags '-w -extldflags "-static"' -o fathom ./cmd/fathom 
make: packr: No such file or directory
make: *** [fathom] Error 1
```

**Comment by lovethebomb** [comment]
`packr` was missing in the README, updated in PR #45 

For now, in your fathom folder, you can run:
```
go get -u github.com/gobuffalo/packr/...
```
and `make build` again!

**Comment by antoaravinth** [comment]
@lovethebomb Thanks, but still seeing the errors:

```
# _/Users/anto/programs/go/fathom/cmd/fathom
/usr/local/go/pkg/tool/darwin_amd64/link: running clang failed: exit status 1
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Error: exit status 2
```

**Comment by dannyvankooten** [comment]
Hi @antoaravinth,

To compile from OSX, the easiest method for now is to set `CGO_ENABLED=0`, as the `sqlite` dependency we use doesn't allow for (fully) static linking.

```
CGO_ENABLED=0 make build
```

We'll get that Packr error fixes, as the Makefile should actually have fetched that dependency for you!

**Comment by dannyvankooten** [comment]
Hi @antoaravinth,

One last Q: what commit # were you at when you first encountered the issue mentioned in the starting post of this thread? 

As of 32693be2b03a5ecf37ff1b1cead82f20cf375afd, the `make` task should automatically install the packr dependency, but somehow it looks like that did not happen for you. Unless you were at a previous commit of course, as the commit is only 2 days old.

Let me know please. :)

**Comment by antoaravinth** [comment]
@dannyvankooten Awesome, thanks. Now with latest master codebase, it started working :) Closing this issue!
