### ISSUE TITLE
Idea: Unique tracking codes per Fathom instance  

### ISSUE THREAD

**Issue by austinginder** [usefathom/fathom#50]
This was briefly talked about in #36 however I'd like to add some of my thoughts. Tracking multiple websites per Fathom instance would be great. Due to the complexities to site configuring (subdomains, subfolder sites, etc) I propose including an optional unique code which can be added to the tracking code. 

This could function similar to Google's UA code and would allow for a clear way to parse through the data when viewing reports (per unique code). This would require some spam considering. Maybe each unique code could be assigned to a particular domain. Or even simpler, just give a way to parse the domain(s) you want when viewing the reports per each unique code. Like only show me unique code (XX-12345) from my site https://anchor.host and ignore the rest (like spammers who ninja tracking codes).

Possible use cases for unique codes include:
- Multiple websites
- Separate initiates on the same website

**Comment by hchouhan** [comment]
+1 for that.

**Comment by rosswintle** [comment]
I confess, my biggest surprise when I got Fathom v1.0 up and running was that it only seemed to track one site. My attempt at my own analytics just uses the referrer from the page hit to match a site that's registered in the database. I'd not considered that you could get spam from people faking the referrer. I'll have to find a way to mitigate that.

**Comment by iskrisis** [comment]
I manage around 20 very small low traffic websites and for that usecase Fathom would be amazing. I run Matomo (piwik) now and its bloated + it needs mysql (which i keep on server just for that). Go + sqlite seems to be so great choice in this case.

Keeping my fingers crossed

**Comment by deanpcmad** [comment]
I manage a couple of small sites so would also like this

**Comment by dannyvankooten** [comment]
Now that our [hosted Fathom offering](https://usefathom.com/) is out of the door, this is pretty much our top priority now. So rest assured that this'll land in Fathom very soon.

**Comment by cweagans** [comment]
Super excited to give this a spin :)

**Comment by m1guelpf** [comment]
@dannyvankooten How should we upgrade?

**Comment by austinginder** [comment]
@m1guelpf You'll have to [compile from the latest source code](https://github.com/usefathom/fathom#installation) or wait for an [official release](https://github.com/usefathom/fathom/releases).

@dannyvankooten Gave it a try. I was able to add new sites however it looks like the only one gathering data is the primary site.  Is that because the stats are computed daily? Or maybe something is broken. Here's what my database scheme looks like. The daily tables only have records with site_id equal to 1. I do see some data relating to other sites starting to fill up the pageviews table. 

```
MariaDB [fathom]> show tables;
+----------------------+
| Tables_in_fathom     |
+----------------------+
| daily_page_stats     |
| daily_referrer_stats |
| daily_site_stats     |
| migrations           |
| pageviews            |
| sites                |
| users                |
+----------------------+
7 rows in set (0.00 sec)

MariaDB [fathom]> select * from migrations;
+------------------------------------------------------+---------------------+
| id                                                   | applied_at          |
+------------------------------------------------------+---------------------+
| 1_initial_tables.sql                                 | 2018-05-10 19:37:07 |
| 2_known_durations_column.sql                         | 2018-05-30 20:31:27 |
| 3_referrer_group_column.sql                          | 2018-06-05 01:35:54 |
| 4_pageview_id_column.sql                             | 2018-07-20 16:57:03 |
| 5_create_sites_table.sql                             | 2018-10-09 16:11:38 |
| 6_add_site_tracking_id_column_to_pageviews_table.sql | 2018-10-09 16:11:38 |
| 7_add_site_id_to_site_stats_table.sql                | 2018-10-09 16:11:38 |
| 8_add_site_id_to_page_stats_table.sql                | 2018-10-09 16:11:38 |
| 9_add_site_id_to_referrer_stats_table.sql            | 2018-10-09 16:11:39 |
+------------------------------------------------------+---------------------+
9 rows in set (0.00 sec)
```

**Comment by dannyvankooten** [comment]
Hey @austinginder,

Good catch! We weren't quite there yet with regards to the actual stats aggregation for multiple istes, but the latest master commit should do it. Things should be pretty stable from here on as we make final preparations for an official v1.1 release!

**Comment by austinginder** [comment]
Looks like it's working!

**Comment by cweagans** [comment]
Sorry to badger, but when do you anticipate tagging a new release?

**Comment by dannyvankooten** [comment]
Monday!

**Comment by cweagans** [comment]
I've been playing with this a bit, and I'm not seeing how to actually use it. Is there a UI for switching between the different sites in the dashboard?

**Comment by sdenike** [comment]
> I've been playing with this a bit, and I'm not seeing how to actually use it. Is there a UI for switching between the different sites in the dashboard?

Same here, I assume that I am missing something?
