### ISSUE TITLE
Clean docker-build returns missing npm error

### ISSUE THREAD

**Issue by kliptonize** [usefathom/fathom#51]
Steps to reproduce:
1. `git clone fathom-repo`
2. `ls /path/to/fathom`
3. `docker build -t fathom .`

--> throws:
```
Step 4/10 : RUN go get -u github.com/gobuffalo/packr/... && make docker
 ---> Running in a787be7b7c11
if [ ! -d "node_modules" ]; then npm install; fi
/bin/sh: 1: npm: not found
Makefile:38: recipe for target 'assets/build' failed
make: *** [assets/build] Error 127
The command '/bin/sh -c go get -u github.com/gobuffalo/packr/... && make docker' returned a non-zero code: 2
```

(Docker version: 18.03.1-ce-mac65 (24312))

**Comment by kliptonize** [comment]
(Obviously, one could run `npm install` to fix the need for the `node_modules`-folder, but that just throws another error when the `gulp.js`-file is run: 
```
/usr/bin/env: 'node': No such file or directory```
(First line of gulp.js, trying to use the non-existing node-env.

**Comment by jaynagpaul** [comment]
This can be fixed by prepending 
```
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
RUN apt-get install -y nodejs
```

to the Dockerfile before `RUN go get -u github.com/gobuffalo/packr/... && make docker`

**Comment by kliptonize** [comment]
Although that does fix the specific error, but it throws another:
```Error: Missing binding /go/src/github.com/usefathom/fathom/node_modules/node-sass/vendor/linux-x64-64/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 10.x

Found bindings for the following environments:
  - OS X 64-bit with Node.js 8.x
```

Tried adding `npm rebuild node-sass --force` to the make file, as interwebz suggested, but the error persists

**Comment by dannyvankooten** [comment]
Hey @kliptonize,

The Docker built uses a two-step process where it first compiles the binary inside a Docker container before proceeding to building the final container. The previous `Makefile` however was instructing Docker to also build the client-side assets inside that container, something that introduces unnecessary complexity if you ask me.

If you build the assets on your local machine before running the `docker build` command (using the latest `master`) then everything should be working as expected.


```
git clone fathom-repo
cd /path/to/fathom
make assets/build
docker build -t fathom .
```

**Comment by kliptonize** [comment]
Thanks @dannyvankooten, that's fixed! 👍

**Comment by infomedia0** [comment]
> This can be fixed by prepending
> 
> ```
> RUN curl -sL https://deb.nodesource.com/setup_10.x | bash -
> RUN apt-get install -y nodejs
> ```
> 
> to the Dockerfile before `RUN go get -u github.com/gobuffalo/packr/... && make docker`

worked like a charm, thank you
