### ISSUE TITLE
Support for more authentication providers

### ISSUE THREAD

**Issue by bramvdbogaerde** [usefathom/fathom#66]
Currently the credentials of the user can only be retrieved from the current datastore.

I think it could be useful to support other providers like an LDAP instance used in many companies and organisations. 

In order to implement this I think that the authentication code should be abstracted into something like a provider interface. So that the user can configure multiple authentication providers over which we can iterate when we need to check a username-password combination.

I can help with that in a few weeks if this functionality is desired.

**Comment by dannyvankooten** [comment]
Hey @bramvdbogaerde,

Sounds awesome, definitely open to it. Current authentication is rather simplistic so would love to abstract into something more generic. That said, I don't have too much experience with LDAP so would love some guidance there, if at all possible.

**Comment by bramvdbogaerde** [comment]
As a mentioned earlier, I want to help, both with creating the abstraction and with the LDAP priovider.
I also have a working LDAP setup so I can test the LDAP provider against that.

This is what I propose:

* Creating an abstract `Provider` interface, with methods that are along the following lines:
    - GetUserByName: get a user by it's name. This is only for presentational purposes when you want for example to display the name of the user after it has logged in
    - Authenticate: tries to authenticate the user with given password and username
* Adding an array of those abstract providers to the Api struct, so that the providers can be accessed
* Populating the array based on user provided configuration

After that we have the basic abstractions to implement serveral authentication providers. The first thing to do then is to move the existing code to a provider. And then we can start implementing other providers, like an LDAP provider.

What do you think, would this fit in to the existing architecture?

**Comment by jhabdas** [comment]
This might be helpful. Maybe.

https://github.com/go-gitea/gitea/blob/master/integrations/auth_ldap_test.go

**Comment by JackEllis** [comment]
@bramvdbogaerde Appreciate the input. We've decided to keep things simple, and avoid external authentication. The purpose of Fathom is to be a simple, lightweight solution for analytics, and adding one additional authentication method sets precedent to add others, and we don't want to get into this.
