### ISSUE TITLE
Contribution guidelines?

### ISSUE THREAD

**Issue by bhox** [usefathom/fathom#67]
Hey ya'll, awesome project, love the idea.

I've been working on a privacy-friendly (but not open source web analytics) product for a few years, and would love to contribute my learnings towards a few features that lots of folks have mentioned. 

Could you publish some contribution guidelines and/or a roadmap I can see if my ideas line up with yours?

**Comment by pjrvs** [comment]
We're working on a roadmap currently, we'll be publishing it soon.

**Comment by bhox** [comment]
Awesome, looking forward to it
