### ISSUE TITLE
Better measurements of time-on-page for single page visits

### ISSUE THREAD

**Issue by da2x** [usefathom/fathom#70]
Prototype tracking code that can track time-on-page per page and thus also better measurements of time-on-site. I’m dumping it here for discussion about the technique rather than implement this in a pull request.

```
function fathom_update_visibility_timer(unload = false) {
  var time_now  = new Date();
  var new_state = document.visibilityState;
  var old_state = window._fathom.visibility;
  var start_timer = (old_state == 'hidden' && new_state == 'visible');   
  var stop_timer  =  
    (old_state == 'visible' && new_state == 'hidden')   ||  // page became hidden (or unloaded in Firefox)
    (old_state == 'visible' && new_state == 'unloaded') ||  // standard unload
    (old_state == 'visible' && unload)                  ||  // compatible unload
    (unload && new_state === undefined);                               // unload in legacy browser
  stop_timer = stop_timer && window._fathom.timestamp !== undefined;   // timer not running

  if (start_timer) {
    window._fathom.visibility = new_state;
    window._fathom.timestamp = time_now;
  }
  if (stop_timer) {
    window._fathom.visibility = new_state;
    window._fathom.timer += (time_now - window._fathom.timestamp) / 1000;
    delete window._fathom.timestamp;
} }
document.addEventListener('visibilitychange', fathom_update_visibility_timer);

function fathom_collector()
{
  if (!window._fathom)
    return false;
  if (document.visibilityState && document.visibilityState == 'prerender')
    return false;

  fathom_update_visibility_timer(true);

  var data = JSON.stringify({"page": document.location.path, "time": Math.round(window._fathom.timer)});
  delete window._fathom;

  if (navigator.sendBeacon && !navigator.sendBeacon('/collect', data);
  {
    var x=new XMLHttpRequest();
    x.setRequestHeader('Content-Type', 'application/json');
    x.open('POST', '/collect', 1);
    x.send(data);
} }

window._fathom = {"timer": 0, "timestamp": new Date(), "visibility": document.visibilityState};


window.addEventListener('beforeunload', fathom_collector);
window.addEventListener('unload', fathom_collector);
```

There is no cut-off for session length. If a page is left open for hours or the system sleeps/hibernates the counter will track this as visible time. Server-side needs to cut off page-times at an upper limit like 30 minutes.

----

Pros:
* Look ma’! No cookies!
* More accurate time-on-page even for single-page visits.
* Beacon API unloads and navigates between webpages faster, especially on slower devices.
* Critical initial page load time isn’t delayed by analytics submission request.

Cons:
* Legacy browsers count page-session lifetime rather than page-visibility time. Skews stats. (Could just not track time for these browsers.)
* XMLHttpRequest only have about 2 seconds to submit data onunload in legacy browsers before the page is fully unloaded. Beacon API doesn’t have this limitation.
* Pageviews may not be counted until an unspecific time in the future or not at all if the browser exits or goes offline.
* Unload handling is inelegant but done this way to get it done as early as possible in as many browsers as possible. (Due to XHR time limit on unload.)

----

The above is adopted from [what I’ve built for Ctrl blog](https://www.ctrl.blog/assets/js/analytics.js). The data collection object and JSON serialization method used there is much improved over the above example, but I felt that would distract from the collector and time-on-page counter. The code in this issue is licensed with the [same license as the project](https://github.com/usefathom/fathom/blob/7d7121cf148773263a59f3a3c3458f8860654c5f/LICENSE).

**Comment by ckluis** [comment]
Looking good, if we can track page-load time without cookies too this could replace google analytics in a lot of scenarios.
