### ISSUE TITLE
ERRO[0007] error handling request  error="database is locked"

### ISSUE THREAD

**Issue by ahmedash95** [usefathom/fathom#72]
On a +15k concurrent traffic, it gives me a `database is locked` error, I know its from **SQLite** database but what issue cause this locking?

**Comment by prologic** [comment]
SQLite is not *great* for concurrent writes. You want to use a database more suited to high volume write transactions.

**Comment by ahmedash95** [comment]
I'm new to fathom, so what is available databases to use instead of sqlite ?

**Comment by prologic** [comment]
Pretty sure you can use mysql. Follow the docs on [custom configuration](https://github.com/usefathom/fathom/wiki/Configuration-file)

**Comment by prologic** [comment]
MySQL will at least give you better concurrent write performance; especially on MyRocks. YMMV

**Comment by ahmedash95** [comment]
Thanks @prologic for ur help.
