### ISSUE TITLE
How do i register for an fathom account while i'm running docker ? 

### ISSUE THREAD

**Issue by ngprnk** [usefathom/fathom#75]
I'm not able to log in while running Docker. I can't seem to find any instructions on how to register for a fathom account while running Docker.

**Comment by lovethebomb** [comment]
You need to run the register command on the container you've just spinned up.

Run `docker run -d -p 8080:8080 usefathom/fathom:latest`, to start fathom, then you can find the container name or ID with `docker ps`.

Replace `$container_name` with the name/id, simply run : 
```
docker exec $container_name ./fathom --email=my-email@domain.tld --password=my-secure-password
```

**Comment by ngprnk** [comment]
Thanks 👍  works :)

**Comment by lovethebomb** [comment]
@ngprnk @dannyvankooten this issue can be closed! :)
