### ISSUE TITLE
304 HTTP Responses (No Stats)

### ISSUE THREAD

**Issue by mcrosson** [usefathom/fathom#78]
When running Fathom I'm noticing that the first GET of tracker.js is receiving a 200 HTTP response code but subsequent GETs are receiving a 304 response.

When the 304 responses happen the stats in the main Fathom UI are not updating.

Has this been seen before? Is there anything I can do for troubleshooting?

Edit : This affects Firefox, Chrome and Edge. IE7 seems to be OK.

**Comment by lovethebomb** [comment]
If you are using a reverse proxy in front of fathom (nginx or Apache for example), make sure that you're not caching static files.

**Comment by mcrosson** [comment]
Would the following header directive be the most appropriate choice for Fathom?

header / "no-store"

**Comment by mcrosson** [comment]
To amend my previous comment and to thank @lovethebomb for the suggestion.

Disabling caching if using a reverse proxy solved the 304 responses.

header /tracker.js Cache-Control "no-store" solved my issue
