### ISSUE TITLE
Stats Not Updating

### ISSUE THREAD

**Issue by mcrosson** [usefathom/fathom#79]
I am running Caddy as a reverse proxy for fathom and Postgresql as a storage engine. I can see the /collect?sid=blah requests in the Fathom logs but the main Fathom web UI with stats doesn't seem to be updating.

Any help/insight would be appreciated.

Caddy Config
```
fathom.domain.tld {
    log /var/log/caddy/git.fathom.log

    proxy / fathom_docker:8080 {
        transparent
    }

    header /tracker.js Cache-Control "no-store"
}
```

Fathom Config

```
FATHOM_DEBUG=true
FATHOM_SERVER_ADDR="8080"
FATHOM_DATABASE_DRIVER="postgres"
FATHOM_DATABASE_NAME="fathom"
FATHOM_DATABASE_USER="fathom"
FATHOM_DATABASE_PASSWORD="Test1234"
FATHOM_DATABASE_HOST="192.168.0.100"
FATHOM_SECRET="ASecretHere"
```

**Comment by mcrosson** [comment]
Fathom Logs

```
INFO[3296] 172.30.0.1 - - [27/Jun/2018:16:04:57 +0000] "GET /api/stats/site/realtime HTTP/1.1" 200 11
INFO[3298] 172.30.0.1 - - [27/Jun/2018:16:04:59 +0000] "GET /tracker.js HTTP/1.1" 200 5440
INFO[3298] 172.30.0.1 - - [27/Jun/2018:16:04:59 +0000] "GET /collect?sid=sidasdf&p=%2Flollipop-docker&t=Lollipop%20Docker%20-%20%5Bgit%5D%20Lollipop%20Cloud&r=&u=1&nv=1&ns=1 HTTP/1.1" 0 0
INFO[3307] 172.30.0.1 - - [27/Jun/2018:16:05:08 +0000] "GET /tracker.js HTTP/1.1" 200 5440
INFO[3307] 172.30.0.1 - - [27/Jun/2018:16:05:09 +0000] "GET /collect?sid=sidasdf&p=%2Flollipop-docker%3Fsort%3D%26page%3D2%26q%3D%26tab%3D&t=Lollipop%20Docker%20-%20%5Bgit%5D%20Lollipop%20Cloud&r=&u=1&nv=1&ns=1 HTTP/1.1" 0 0
INFO[3310] 172.30.0.1 - - [27/Jun/2018:16:05:11 +0000] "GET /tracker.js HTTP/1.1" 200 5440
INFO[3310] 172.30.0.1 - - [27/Jun/2018:16:05:11 +0000] "GET /collect?sid=sidasdf&p=%2Flollipop-docker%2Fcaddy&t=lollipop-docker%2Fcaddy%20-%20%5Bgit%5D%20Lollipop%20Cloud&r=&u=1&nv=1&ns=1 HTTP/1.1" 0 0
INFO[3316] 172.30.0.1 - - [27/Jun/2018:16:05:17 +0000] "GET /api/stats/site/realtime HTTP/1.1" 200 11
```

**Comment by dannyvankooten** [comment]
Hey, that's strange. Can you look into your connected database and see if the `pageviews` table has entries (if your stats still have not updated by now)?

**Comment by mcrosson** [comment]
@dannyvankooten I'm not seeing any rows in the pageviews table. I do see the /collect?blah calls coming through in fathom though on the server side.

I have the fathom front end at https://git.fathom.lollipop.holdmybeer.solutions/ (username anon@anon / password anon) and the tracking code is in the footer of https://git.lollipop.holdmybeer.solutions if you'd like to see what some of the requests look like and/or stats page.

The stats that were processed were during my initial testing with IE11. Also : I just did a quick check with IE11 again and the stats table is being populated if i use IE11.

I currently have ```    header / Cache-Control "no-store"``` set in my Caddyfile to see if it I needed to disable the cache on more files/assets than tracker.js

**Comment by mcrosson** [comment]
I am testing Chrome on Windows 7 with the Do Not Track setting turned OFF as well

**Comment by dannyvankooten** [comment]
Could it be that Caddy is somehow not forwarding the request HTTP referer, [resulting in this line evaluating to true](https://github.com/usefathom/fathom/blob/master/pkg/api/collect.go#L28)?

**Comment by dannyvankooten** [comment]
Ah, got it. Definitely something we should fix in Fathom.

Because your page has `<meta name="referrer" content="no-referrer" />`, Fathom discards the request. I knew I was overseeing something when relying on the referer header versus adding it in the URL parameters.

**Comment by mcrosson** [comment]
Confirmed working on my end :+1:
