### ISSUE TITLE
Device and location stats for Fathom

### ISSUE THREAD

**Issue by austriker27** [usefathom/fathom#82]
Super excited for this project and can't wait for more releases. Fantastic work gentlemen. 

The two vital stats that are missing right now I think, are device and location information. Both pretty important stats to know as a developer. 

I know its an early release at this point but once those two stats are added I'm definitely going to use fathom for all my websites! Your UI and design is so polished, and I like your focus on simplicity and privacy.

**Comment by dewey** [comment]
I'd be interested in helping with the user agent implementation, from what I see it needs to be added to the pageview table / model. Later on the aggregator could use something like https://github.com/mssola/user_agent to normalize it a bit, maybe we could even flag them as "Bot" if it's a known bot and somehow reflect that in the UI? Not sure if that's useful for people.

As for the geo location: I guess we want to avoid storing the IP for legal reasons so we'd need to do the geo lookup before persisting it somehow without slowing down the ingestion?

**Comment by jhabdas** [comment]
Both of these features seem like something that could be used to help fingerprint user agents, which seems at odds with the intent of simple analytics.

> Both pretty important stats to know as a developer.

What would you use them for? How are they important?

**Comment by jhabdas** [comment]
Both of these features could be used to help fingerprint user agents, which seems at odds with the spirit of this project.

> Both pretty important stats to know as a developer.

What would you use them for? How are they important?

**Comment by austriker27** [comment]
> What would you use them for? How are they important?

Device: This is important to know as you develop the responsiveness and screen sizes of a website
Location: This is important to know so you can develop aspects of a website related to language, and culture

**Comment by pjrvs** [comment]
At this time it does feel like collecting data like that is at odds with this project. That could change in the future, but even if it did, it would be aggregate or overall trend data, not specific to each user and their visit to a site.

**Comment by austriker27** [comment]
Yeah I dont see any need to collect data specific to each user, and would agree it conflicts with the project's mission. 

Aggregating the data as a whole would be useful from a dev POV!

**Comment by jhabdas** [comment]
a sly workaround for collecting geo and referrer data: https://bit.ly. simply wrap up your image header in the link and away you go. note bitly collects ip so it kinda defeats the point of using a privacy analytics service such as fathom and use of such a service should probably be disclosed if you want to be transparent about your data collection practices. that said, if anyone knows of a similar service which _doesn't_ collect ip I'd be much obliged if you'd let me know.

**Comment by jhabdas** [comment]
> Device: This is important to know as you develop the responsiveness and screen sizes of a website

If the data were unique to a specific website I could see this being useful. Otherwise, why not use aggregate screen size data (by country) from DeviceAtlas or similar?

> Location: This is important to know so you can develop aspects of a website related to language, and culture

From a security and privacy perspective that should probably come using something like [GeolocationSensor](https://wicg.github.io/geolocation-sensor/) interface. The problem there is only some users will choose to opt into this kind of intrusion so the data collected may not carry statistical significance—especially if catering to a privacy-conscious audience.

**Comment by jhabdas** [comment]
> Device: This is important to know as you develop the responsiveness and screen sizes of a website

If the data were unique to a specific website I could see this being useful. Otherwise, why not use aggregate screen size data (by country) from DeviceAtlas or similar?

> Location: This is important to know so you can develop aspects of a website related to language, and culture

From a security and privacy perspective that should probably come using something like [GeolocationSensor](https://wicg.github.io/geolocation-sensor/) interface. The problem there is only some users will choose to opt into this kind of intrusion so the data collected may not carry statistical significance—especially if catering to a privacy-conscious audience—so it's possible you end up translating for the wrong audience anyway.

**Comment by jhabdas** [comment]
> Device: This is important to know as you develop the responsiveness and screen sizes of a website

If the data were unique to a specific website I could see this being useful. Otherwise, why not use aggregate screen size data (by country) from DeviceAtlas or similar?

> Location: This is important to know so you can develop aspects of a website related to language, and culture

From a security and privacy perspective that should probably come using something like [GeolocationSensor](https://wicg.github.io/geolocation-sensor/) interface. The problem there is only some users will choose to opt into this kind of privacy intrusion so the data collected may not carry statistical significance and so it's possible you end up translating for the wrong audiences anyway.

**Comment by colinrubbert** [comment]
I agree that this would be useful information to have at our fingertips for targeted user development, which seems extremely sleezy and at odds of the project, but I think if we just gather statistics on user agent and general region say (US, Canada, China, South Africa or by States/Provinces) that would go a long way to helping out developers to create the best experience possible for their users.

For instance, the company I work for has 3 primary focuses in our organization; contract packaging, residential treatment for substance use disorders, and sober living. If all goes well and I can build out a reasonable product it will have a SaaS division as well. 

Contract packaging: the majority of our customers are corporate type clients; old, stodgy paper mill type industries. These companies do not use the latest and most advanced browsers. Most of them still use IE as their primary browser on desktop and I've still got roughly 1% of my traffic being IE 6! With that information I need to take into consideration certain development practices. Getting statistics on that would go a long way to determining what I need to do to support these clients without GA I don't have that information at my fingertips (easily) and something I find to be very useful for my productivity and my time in which I need to focus on something (I am the only IT person and doing sys admin, IT management, help desk, web design/development, and application development). I need to have precision focus.

Residential Treatment & Sober Living: These two divisions are pretty everyday consumer focused, I rarely see IE and if I do it's the latest which gives me more leeway for my development time. Gathering user agent info here is as important, however, getting rough geolocation data can prove to be more useful information for how we present ourselves. Are we a local only addiction recovery community or are we a national community that can expand our reach to other regions in the US and Canada and help more people? If we're starting to getting big hits from say Florida (we're in Wisconsin) then it could be a potential opportunity to fulfill a need that isn't being fulfilled. 

I can see where the line starts to get blurry between useful analytics and gathering user information but if there was a way to get this data subset without compromising our visitors information that would be immensely helpful to me and I'm sure many developers.

Just a simple counter to count specific user-agents and count IP hits from regions could go a long way. This would mean that we're not storing actual user information just counting the hits just like you would from website referrals and such.

We're also a non-profit so we have to compete with for-profit companies on a non-profit budget, which I've been able to do from a technical point of view but I would love to be able to get rid of some services in favor of services that provide better privacy and protection for our customers and users.

**Comment by 54** [comment]
I agree that adding things like this can be dangerous and recognise they can be used to fingerprint. But, quite a few of these dangerous data points have important, real-world use cases that are not malicious.

For example, for my little indie-game, are my users mostly PC users or is there a significant enough mobile user base to justify developing an app? If so, iOS or Android?

I notice a lot of users from Lithuania. How many of them do we really have and how dedicated are they compared to the average American user? Is it worth doing a Lithuanian translation, even though it'll cost a decent bit of money to get done?

Browser language alone doesn't always tell the full story either when it comes to minority languages and dialect differences as well, but knowing that I have users in South Ossetia would tell me there is a good chance they speak Ossetian.

**Comment by ksec** [comment]
I guess it depends, for me privacy is about not being able to individually trace back to its users, much like how Apple are collecting information but they can't fingerprint which pcs of info were coming from which users.

Location, Devices, Browser, Peak Time etc are all very useful information.

**Comment by dangayle** [comment]
I work for a newspaper publisher whose editorial decisions are often directed by our analytics. For instance, we need to know at what times to publish bigger stories to have the largest impact but have entirely different traffic spikes for desktop and mobile and we need to be able to distinguish. We also know that if a story's traffic is coming largely from mobile that the story has been picked up on social media and needs more play on our website. In all of these cases, we don't need PII, we need aggregate statistics.

**Comment by jhabdas** [comment]
> In all of these cases, we don't need PII, we need aggregate statistics.

Sounds like a separate issue, then, yeah? This issue is about collecting device information and location stats – currently an [opt-in feature](https://www.w3.org/TR/geolocation-sensor/) on the Web. If you really need aggregated statistics about location why not parse your log files?

**Comment by jhabdas** [comment]
> In all of these cases, we don't need PII, we need aggregate statistics.

Sounds like a separate issue, then, yeah? This issue is about collecting device information and location stats – currently an [opt-in feature](https://www.w3.org/TR/geolocation-sensor/) on the Web. If you really need aggregated statistics why not parse your log files and give the data to MaxMind?

**Comment by jhabdas** [comment]
> In all of these cases, we don't need PII, we need aggregate statistics.

Sounds like a separate issue, then, yeah? This issue is about collecting device information and location stats – currently an [opt-in feature](https://www.w3.org/TR/geolocation-sensor/) on the Web. If you really need aggregated statistics why not parse your log files as opposed to giving away data to the likes of MaxMind?

**Comment by jhabdas** [comment]
> In all of these cases, we don't need PII, we need aggregate statistics.

Sounds like a separate issue, then, yeah? This issue is about collecting device information and location stats – currently an [opt-in feature](https://www.w3.org/TR/geolocation-sensor/) on the Web. If you really need aggregated statistics why not parse your log files as opposed to giving away data to the likes of MaxMind?

> I work for a newspaper publisher whose editorial decisions are often directed by our analytics.

This is a ruse. The decisions are based on a profit motive. News should break when it breaks.

**Comment by Kiura** [comment]
@54, Please don't provide translations based on location, that is so wrong in many ways. I live in Germany but I don't understand a word in German and hate websites that use my location to guess which language I speak. I set my language preference in the browser (I think browser also uses my system language), So if I am using English throughout my system then I probably speak English. Use the language you get from the browser.

**Comment by Kiura** [comment]
As for this feature I think it is very useful and as a developer I only need an aggregated data (wouldn't trust any website gathering any statistics that can fingerprint me). However, I would only add this option if it is optional (it would be nice to be able to disable this kind of features or manually turn on features one needs).

**Comment by 54** [comment]
@kiura nobody said anything about selecting the front-end language based on geolocation. And, in general, i18n shouldn’t be handled by your analytics software. Rather, my point is simply that such analytics can be useful to tell you more about the potential needs of your user base and allow you to prioritize resources (e.g., localization efforts and so on); no need to try and school me - as a foreigner in Russia, I am aware of how to do localization without making people angry 😉

**Comment by Kiura** [comment]
@54, My apologies if I sounded harsh or disrespectful. I probably misunderstood you, for the scenario you described it seems perfectly valid and useful.

**Comment by jhabdas** [comment]
I'm just going to leave this here for the next guy:

> Fathom does not process an excessive amount of data about each website user to achieve this. Unlike many other analytics services, Fathom does not gather data points such as IP address, device configuration, geo-location data.

https://usefathom.com/data/

Feel free to 🚲🏭it only applies to the EU but if you watched Zuck or Pachai testify in front of congress you probably have a pretty good idea how much senators in the US are swooning over GDPR privacy legislation. If you really want device and location stats [scrape your logs](https://goaccess.io/).

**Comment by JackEllis** [comment]
No plans to introduce this to the OS version at present. Looking to keep it simple. This may change!

**Comment by jcuenod** [comment]
To be honest, this is all I want in terms of device info (I don't even care about the edge cases this doesn't catch):

```
function getPlatformType() {
	if(navigator.userAgent.match(/mobile/i)) {
		return 'Mobile';
	} else if (navigator.userAgent.match(/iPad|Android|Touch/i)) {
		return 'Tablet';
	} else {
		return 'Desktop';
	}
}
```

**Comment by Okozzie** [comment]
> No plans to introduce this to the OS version at present. Looking to keep it simple. This may change!

Any updates for this?
