### ISSUE TITLE
Make tracker.js backend independent

### ISSUE THREAD

**Issue by arikfr** [usefathom/fathom#83]
It will be great to be able to use `tracker.js` with other backends than `fathom` itself. Personally, I'll be happy to use it with a simple Serverless function (AWS Lambda or similar), that logs the data into some database.

Are you open to extracting `tracker.js` into its own repository?

**Comment by dannyvankooten** [comment]
Hey @arikfr,

Sorry, not right now. At this stage I really prefer a monorepo for simplicity reasons.
