### ISSUE TITLE
self-hosted?

### ISSUE THREAD

**Issue by dalu** [usefathom/fathom#86]
Is this self-hosted?
Because 
<blockquote>
Register your user account: fathom register --email=<email> --password=<password>
</blockquote>
And moreover, is the generated data stored on "my host" or "your host"?

**Comment by dannyvankooten** [comment]
Hi @dalu,

Yes, this is fully self-hosted at this point. No third services are used.

The command registers / creates the user in your local database (the one you defined in [your configuration file](https://github.com/usefathom/fathom/wiki/Configuration-file)). It's used for authenticating with your dashboard, running on your server.

Cheers!
