### ISSUE TITLE
Scope referers (and eventually other stats) by path

### ISSUE THREAD

**Issue by tomas** [usefathom/fathom#89]
Hi! Great project.

I'm not sure if you've already thought of this, but it would be nice to be able to filter the stats on the right pane by path. So when I click on a path, instead of redirecting to that page, Fathom would filter the results shown on the right. This would be a huge help in understanding the user behaviour on different sections of a website.

And by the way, why am I seeing three different results for the same path? Shouldn't they be grouped together?

![image](https://user-images.githubusercontent.com/10574/42542981-7e1c1826-8477-11e8-8880-664439114f73.png)

Thanks!

**Comment by dannyvankooten** [comment]
Hey @tomas, thanks!

> I'm not sure if you've already thought of this, but it would be nice to be able to filter the stats on the right pane by path. So when I click on a path, instead of redirecting to that page, Fathom would filter the results shown on the right. This would be a huge help in understanding the user behaviour on different sections of a website.

Yes, this is actually pretty much what we're intending to do. #25 touches upon this lightly, but let's keep this issue open to track progress on this feature.

> And by the way, why am I seeing three different results for the same path? Shouldn't they be grouped together?

Could you hover the links or check your page source to compare the actual `href` attributes of these 3 links? I'm guessing they are different subdomains, but please do let me know if they are in fact the same URL.

**Comment by tomas** [comment]
You're right, different subdomains. Then I guess the UI should show this to avoid confusion, and/or maybe show a select box to allow filtering data per tracked domain. This might also help resolve the former.

**Comment by tomas** [comment]
@dannyvankooten Any progress on this? :)

**Comment by mgibbs189** [comment]
@tomas this is an excellent idea, and surprising it wasn't part of the MVP.

Clicking on a **referrer** could drill-down the pages list, or clicking on a **page** could drill-down the referrer list. Seems like a basic but extremely useful feature.

@dannyvankooten are there any technical limitations preventing this from happening?

**Comment by tomas** [comment]
Hi, any news regarding this?

**Comment by dantuluri** [comment]
+1

**Comment by tomas** [comment]
@JackEllis so no news?

**Comment by JackEllis** [comment]
@tomas we aren’t adding this to Fathom Lite

**Comment by tomas** [comment]
I see. I guess I'll move on to Kindmetrics then.

Thanks anyway!
