### ISSUE TITLE
Provide support for different databases?

### ISSUE THREAD

**Issue by tboerger** [usefathom/fathom#9]
I would be cool if ana works with different databases. To have some abstraction and some kind of models I would suggest the usage of github.com/russross/meddler. If you also want to have an idea how to use it in the wild I would suggest to take a look at https://github.com/drone/drone/tree/master/store/datastore which is using it quite long and also with bigger load.

**Comment by zet4** [comment]
+1 for Postgres support

**Comment by dannyvankooten** [comment]
Hey guys,

Thanks for the suggestions, meddler looks pretty neat. I'd have to take a look at abstracting away the SQL as I am not too sure whether some of queries needed for aggregating data into a more performing format can be abstracted away that easily.

What would be a benefit of PostgreSQL over MySQL? The raw `pageviews` table in Ana has to be optimized for loads of `INSERT` statements (and very few reads) and from what I've read, MySQL is much more performant when it comes to that than Postgreq.

**Comment by zet4** [comment]
I just want postgres support as that's the only DB I use on my server and would rather not install mysql only for ana

**Comment by tboerger** [comment]
Meddler still gives you enough power to write performant queries. Everybody got different preferred databases, there are enough people that want to use MySQL/MariaDB or PostgreSQL or MSSQL ;)

**Comment by hitminion** [comment]
@dannyvankooten take a look on clickhouse https://github.com/yandex/ClickHouse https://clickhouse.yandex/ . It's a good choice for you application, especially for tables heavy on inserts (views, user-actions, visits, etc. ) moreover you can benefit from mixin clickhouse with postgres together (for customer related data)

**Comment by tboerger** [comment]
Great to see that integrated
