### ISSUE TITLE
Postgres DSN needs `sslmode` option

### ISSUE THREAD

**Issue by brentjanderson** [usefathom/fathom#90]
When running fathom using Docker with a linked postgres container for storage, the following crash occurs:

```
time="2018-07-11T05:29:11Z" level=info msg="Fathom 1.0.0"
time="2018-07-11T05:29:11Z" level=warning msg="Missing configuration file. Using defaults."
panic: pq: SSL is not enabled on the server
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x81fbcc]
```

I propose including an additional configuration parameter `FATHOM_DATABASE_PG_SSLMODE` for setting the postgres SSL mode parameter. Under the described Docker configuration, setting such a configuration value to `disable` would fix the problem. The correction needs to happen in [config.go line 21](https://github.com/usefathom/fathom/blob/7f61259df35c6d28fd05ac69953f181214a55241/pkg/datastore/sqlstore/config.go#L21).

I can issue a PR for this change if the described solution is acceptable.

**Comment by dannyvankooten** [comment]
Hey, thanks for chiming in! Definitely open for a PR on this, although I'll try to take a look myself as well.

Relates to #80

**Comment by dannyvankooten** [comment]
It turned out as `FATHOM_DATABASE_SSLMODE` because it could also be useful for connecting with a MySQL database, setting the `tls` connection parameter.

Thanks for the heads up & help here!

**Comment by BlueHatbRit** [comment]
Sorry for tagging on a closed issue, I just tried hosting via Kube (on gcp) with a postgres database and it took me quite a while to find this issue which indicates that `FATHOM_DATABASE_SSLMODE` was the cause of the invalid memory error.

I feel like there should be a default set or at least a warning in the configuration documentation for postgres users. I've not tried MySQL so this may also apply for MySQL users as well.

I see you're using a Wiki for most docs which means a PR can't be submitted but this seems like a sensible place to put it?

**Comment by dannyvankooten** [comment]
Hey @BlueHatbRit,

No worries - I totally agree. We're launching a searchable documentation site soon. Until then, I've added in the following note under the [Configuration section](https://github.com/usefathom/fathom/wiki/Configuration-file).

<img width="352" alt="image" src="https://user-images.githubusercontent.com/885856/43064597-acfed114-8e5f-11e8-9b8a-71c90cb1eecb.png">

Sorry you had to spend time on this.

**Comment by BlueHatbRit** [comment]
Fantastic thanks @dannyvankooten for the quick turn around on that, hopefully it'll help some people out. That was the only hurdle for getting fathom running for me, great to see it resolved.
