### ISSUE TITLE
usefathom.com lacks IPv6 support

### ISSUE THREAD

**Issue by tambry** [usefathom/fathom#91]
usefathom.com can't be accessed using IPv6.

Steps for fixing this:
* [Enable IPv6 on droplet](https://www.digitalocean.com/docs/networking/ipv6/how-to/enable/)
* Add the droplet's IPv6 address to the various domains

**Comment by pjrvs** [comment]
thanks tambry - just added IPv6 support to the droplet and updated our DNS. for some reason it doesn't seem to be working (when i ping6 the newly assigned IPv6 address, it fails). any suggestions? i added the AAAA record to our registrar and followed the DO instructions.

**Comment by tambry** [comment]
Thanks for looking into this!

What version of Ubuntu are you using?  
Can you ping `ipv6.google.com`?

If no, then what's the output of `ip address show`? Is the `inet6` interface in `/etc/network/interfaces` configured as shown in the DO help article I linked?

If yes, is the server's firewall configured correctly? Make sure HTTP/HTTPS traffic is allowed through the IPv6 firewall.  
Additionally, if IPv6 pings aren't working you may be blocking ICMPv6 traffic. ICMPv6 is essential for IPv6 to function correctly and you should never block any part of it, unless you really know what you're doing – having it fully enabled is also required for IPv6 to function on some VPS hosts (notably Linode).

Aside from that, you seem to have also forgotten to add the IPv6 address to stats.usefathom.com.

**Comment by pjrvs** [comment]
Ubuntu 16.04.4 LTS on digital ocean.

from the server, no, i cannot ping ipv6.google.com.

`ip address show` gives me:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether c2:09:53:a0:06:78 brd ff:ff:ff:ff:ff:ff
    inet 159.203.25.14/20 brd 159.203.31.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet 10.20.0.6/16 brd 10.20.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::c009:53ff:fea0:678/64 scope link 
       valid_lft forever preferred_lft forever
```

and yes, i configured the `inet6` interface per the DO instructions. i'll look into ICMPv6 traffic and blocking now. i appreciate your help!

i'll also add IPv6 for stats.usefathom.com.

**Comment by tambry** [comment]
If `ip address show` gave you no `scope global` IPv6 address, but you configured the `inet6` interface, then it's probably because you forgot to restart your network service. But since you got around it, what was the actual issue?

And I can confirm that I can now connect to both `usefathom.com` and `stats.usefathom.com` using IPv6.  
Unfortunately connecting `stats.usefathom.com` using IPv6 returns the certificate for `usefathom.com` (why do you have separate certificates for them?). In case you created separate `server`s for IPv4 and IPv6 in the Nginx config and that caused the messup, then remember that you can have multiple `listen` directives in a single `server` block.

**Comment by pjrvs** [comment]
thanks for your help with this! i did actually reboot the first time, but it didn't seem to stick. second reboot fixed it.

for the cert, i believe there are separate certs because we setup a cert on LE for the main site first, the for the demo site way after. although my knowledge/understanding of LE certs is limited (i'm a designer, haha, not a dev). 

but IPv6 is working on both?

**Comment by tambry** [comment]
You can have certs for many subdomains on a single cert. Having a single cert with both subdomains on it would probably make it easier to manage them (and also lessen the load on LE's servers).

IPv6 is working on both, but when loading `stats.usefathom.com` using IPv6 it doesn't actually return the demo dashboard, but rather the main site.

**Comment by pjrvs** [comment]
thanks! i'll see about getting a single cert working for both. 👌

**Comment by pjrvs** [comment]
i'll get to the single cert for both eventually, but as IPv6 is now working on both, i'm closing out this ticket since that update is more an efficiency thing than a bug now.

**Comment by tambry** [comment]
The invalid cert on stats.usefathom.com seems to be back (sorry for the German).

![2018-07-12_17-14-00_chrome](https://user-images.githubusercontent.com/1827708/42638702-020e9b1a-85f7-11e8-9726-5c8dadcc3b41.png)

**Comment by pjrvs** [comment]
ah, it's not binding the cert to IPv6. i'll look into this now...

**Comment by tambry** [comment]
It is, just the wrong one. The one for usefathom.com is returned when visiting stats.usefathom.com.

**Comment by A1bi** [comment]
Seems to be broken again. Can't connect to either of the domains via IPv6. "Network is unreachable"

**Comment by tambry** [comment]
Can confirm:

```
# ping usefathom.com
PING usefathom.com(2001:41d0:401:3200::24a1 (2001:41d0:401:3200::24a1)) 56 data bytes
From 2001:41d0:401::2e (2001:41d0:401::2e) icmp_seq=1 Destination unreachable: Address unreachable
From 2001:41d0:401::2e (2001:41d0:401::2e) icmp_seq=2 Destination unreachable: Address unreachable
From 2001:41d0:401::2e (2001:41d0:401::2e) icmp_seq=3 Destination unreachable: Address unreachable
From 2001:41d0:401::2e (2001:41d0:401::2e) icmp_seq=4 Destination unreachable: Address unreachable
From 2001:41d0:401::2e (2001:41d0:401::2e) icmp_seq=5 Destination unreachable: Address unreachable
```
