### ISSUE TITLE
SSL encryption errors “Not Trusted” on iOS 11.4

### ISSUE THREAD

**Issue by learning-more** [usefathom/fathom#92]
I’m seeing “this connection is not private” errors on Safari in iOS 11.4 when accessing https://stats.usefathom.com. Looking in the cert, I don’t see “stats.usefathom.com” as a subject alternative name. When testing at SSLshopper, I don’t see an error.

**Comment by pjrvs** [comment]
i can't replicate this on iOS 11.4 and safari... or on any browser/device i've got access to.

**Comment by dannyvankooten** [comment]
Weird, I can't seem to replicate this either. I'll close this issue for now, but please do let us know if you can spare any details on this @learning-more.
