### ISSUE TITLE
panic: pq: SSL is not enabled on the server

### ISSUE THREAD

**Issue by Netherdrake** [usefathom/fathom#93]
Is there a way to use a postgres instance that is not behind SSL?

**Comment by jhabdas** [comment]
Relates #90. Take a look here: 

https://github.com/usefathom/fathom/blob/7f61259df35c6d28fd05ac69953f181214a55241/pkg/datastore/sqlstore/config.go#L21

The `dsn` assignment needs `sslmode=disable` or, if data source name is a url a query string param of `sslmode=disable` to disable SSL.

The official `postgres` docker container [appears to support](https://github.com/docker-library/postgres/pull/152#issuecomment-216917400) a `POSTGRES_ENABLE_SSL` environment flag to disable it in the container if you're running through Compose.

**Comment by jhabdas** [comment]
Relates #90. Take a look here: 

https://github.com/usefathom/fathom/blob/7f61259df35c6d28fd05ac69953f181214a55241/pkg/datastore/sqlstore/config.go#L21

The `dsn` assignment needs `sslmode=disable` or, if data source name is a url a query string param, of `?sslmode=disable` to disable SSL.

The official `postgres` docker container [appears to support](https://github.com/docker-library/postgres/pull/152#issuecomment-216917400) a `POSTGRES_ENABLE_SSL` environment flag to disable it in the container if you're running through Compose.

**Comment by dannyvankooten** [comment]
As of a6f9b385a3a015115ec12cffbdc003d3f30935c3, you can set `FATHOM_DATABASE_SSLMODE=disable` in your environment values (or in the [configuration file](https://github.com/usefathom/fathom/wiki/Configuration-file)) to run Postgres or MySQL without SSL.
