### ISSUE TITLE
Don't count or hide visits coming from localhost environments

### ISSUE THREAD

**Issue by HyperTesto** [usefathom/fathom#94]
Hi,
Is there a way to ignore or hide requests coming from localhost environments? 
I have integrated fathom on my blog that is running using Hugo and the visit counter increases a lot since the page I'm working on is automatically reloaded every time i save the source file.
In plus the same page is listed twice on the dashboard. 

Since i am running Fathom behind a reverse proxy i think those requests coming from localhost can be blocked with some policy, but having an option to to this directly in Fathom makes sense to me.

I attach a screenshot of my currently running instance as example
![screenshot_2018-07-12 fathom 1](https://user-images.githubusercontent.com/5920447/42659252-fe5b6148-8627-11e8-97bd-1171a1ba9152.png)

Thanks!

**Comment by jhabdas** [comment]
Your visits won't get recorded if you set `navigator.doNotTrack`.

**Comment by dannyvankooten** [comment]
Hey @HyperTesto,

We're planning on introducing a `domain` setting which, if set, will only track data coming from that domain. 

But until then, I recommend not printing the tracking snippet if on localhost. Here's a sample code snippet for Hugo:

File: `config-dev.toml`
```toml
baseURL = "https://yoursite.example.com/"
fathomURL = ""
```

File: `config-prod.toml`
```toml
baseURL = "https://yoursite.example.com/"
fathomURL = "//yourfathom.com/tracker.js"
```

File: `layouts/partials/footer.html`
```html
{{ if .Site.fathomURL }}
<!-- Fathom - simple website analytics - https://github.com/usefathom/fathom -->
<script>
(function(f, a, t, h, o, m){
	a[h]=a[h]||function(){
		(a[h].q=a[h].q||[]).push(arguments)
	};
	o=f.createElement('script'),
	m=f.getElementsByTagName('script')[0];
	o.async=1; o.src=t; o.id='fathom-script';
	m.parentNode.insertBefore(o,m)
})(document, window, '{{.Site.FathomURL}}', 'fathom');
fathom('trackPageview');
</script>
<!-- / Fathom -->
{{ end }}
```

Cheers!

**Comment by HyperTesto** [comment]
Hi @dannyvankooten ,
thank you for your feedback I'll do as you suggested an if it works i'll try to put together a small guide for Hugo integration.

**Comment by danrocha** [comment]
I'm on a Vue project, so in my `public/index.html` I added a check to the Fathom script:
```html
<!-- Fathom - simple website analytics - https://github.com/usefathom/fathom -->
    <script>
      if (!location.host.includes('localhost')) {
        (function(f, a, t, h, o, m) {
          a[h] =
            a[h] ||
            function() {
              (a[h].q = a[h].q || []).push(arguments);
            };
          (o = f.createElement('script')),
            (m = f.getElementsByTagName('script')[0]);
          o.async = 1;
          o.src = t;
          o.id = 'fathom-script';
          m.parentNode.insertBefore(o, m);
        })(document, window, '//stats.danroc.dev/tracker.js', 'fathom');
        fathom('set', 'siteId', 'LBKOF');
        fathom('trackPageview');
      }
    </script>
<!-- / Fathom -->
```
Do you reckon this is a valid workaround?
